### ISSUE TITLE
Adding Courses from every Org

### ISSUE THREAD

**Issue by CommanderStorm** [joschahenningsen/TUM-Live#1000]
**Is your feature request related to a problem? Please describe.**
Currently, “we” only allow adding courses for various selected orgs (CIT, Management, ED) via this interface:
![image](https://user-images.githubusercontent.com/26258709/232814469-97e7cd78-a8e5-4c19-97e3-36288b991e59.png)

The reason we don't allow any org is that this may become confusing and irrelevant search entries may become more prevalent.

**Describe the solution you'd like**
I would like to either
- give the search engine more signals to sort on
  (number of participants, does its main lecture hall have RBG hardware installed)
- calculate a "likelyhood this lecture has livestreaming enabled" based on historical data and similar-lectures and add this to the signals to sort on
- just allow any org and accept the downside

**Describe alternatives you've considered**
Not doing anything or manually filtering.
Both don't scale quite how we want imo, but can be viable alternatives.

**Additional context**
Should imo be classified as low priority.
This came up because I wanted to suggest one of my BWL Profs to stream his lecture from MW2001 😉
We have patched this by adding Management to the allowlist. One of the courses in the WZW which is currently excluded is https://campus.tum.de/tumonline/WBMODHB.wbShowMHBReadOnly?pKnotenNr=1546258&pOrgNr=15671

**Comment by joschahenningsen** [comment]
Importing all courses and weighing them based on the lecture hall and possibly number of participants seems like a good fit here. This would however significantly increase the load of the course import Cron job as we need to load the calendar and enrollments of every course in existence. (Daily?) 🙈

**Comment by CommanderStorm** [comment]
I can now add such coureses
