### ISSUE TITLE
Upload Camera & Lecture slides as VOD

### ISSUE THREAD

**Issue by mono424** [joschahenningsen/TUM-Live#1006]
**Is your feature request related to a problem? Please describe.**
You cannot upload slides and camera for one VOD.

**Describe the solution you'd like**
Add the possibility to upload two video for one VOD, Camera and Slides.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by joschahenningsen** [comment]
Would be great to be able to upload all 3 versions of the video, camera, presentation **and** comb
