### ISSUE TITLE
When switching the view (e.g. pres -> camera) while a video is playing, the livestream should continue without an additional press of a button 

### ISSUE THREAD

**Issue by LadnerJonas** [joschahenningsen/TUM-Live#1019]
**Is your feature request related to a problem? Please describe.**
When switching the view (e.g. pres -> camera) while a video is playing, the livestream should continue without an additional press of a button.
![image](https://user-images.githubusercontent.com/92096842/236633262-b80c6805-e21f-4bd5-8c72-d0f4f6ff9cbf.png)

**Describe the solution you'd like**
Automatically continue the video

**Describe alternatives you've considered**
A setting on the setting page

**Additional context**
Firefox 112, (arch/manjaro linux)

**Comment by MatthiasReumann** [comment]
More often than not autoplay of videos is blocked by browsers automatically. For Firefox see https://support.mozilla.org/en-US/kb/block-autoplay to change this default behavior.
