### ISSUE TITLE
Videos use native browser controls

### ISSUE THREAD

**Issue by Smail** [joschahenningsen/TUM-Live#102]
About two days ago, all of my browsers started using the browser's native video controls, so big picture mode, playback speed, etc. are missing. I tried Edge, Chrome and Firefox on Windows and Edge (yes, Edge) on Linux. Is this intentional? I really miss the big picture mode.

**Comment by joschahenningsen** [comment]
Hi @Smail I'm super sorry for missing this issue, gmail marked the notification as spam :disappointed: 

I assume you use a touch device? This was intended to make the UI more accessible on mobile/tablet devices. I'll revert the change and think of something else to improve the mobile experience :)

**Comment by joschahenningsen** [comment]
Should be back to the previous state now, let me know if not :) 
On a second thought, the big picture mode could be the default as well.
