### ISSUE TITLE
Subscribe to courses

### ISSUE THREAD

**Issue by MSchreber** [joschahenningsen/TUM-Live#1035]
Ich würde gerne manche Vorlesungen abonnieren können. Denn ich bin z.B. für Operations Research eingeschrieben, dennoch läuft die OR Zentralübung über ein extra Eintrag bei TUM Live. Das heißt ich muss bis ganz nach unten scrollen um die Zentralübung auszuwählen. Könnte ich auch Vorlesungen "abonnieren" für die ich laut system nicht direkt eingeschrieben bin, wäre das Problem nicht da.. Umsetzung maybe durch einen Abo-button bell

**Comment by joschahenningsen** [comment]
Hi, wenn du mit der Maus über den Eintrag der Vorlesung fährst kannst du über die drei Punkte den Kurs "Anpinnen". Ist das etwa, was du dir vorstellst?

https://github.com/joschahenningsen/TUM-Live/assets/44805696/4326eebf-be77-4aed-9af3-13dd05552f30

Andernfalls evtl. in TUMonline für die ZÜ einschreiben?

**Comment by MatthiasReumann** [comment]
After #1029 the `pin` feature @joschahenningsen described will behave quite similar to the subscribe feature of YouTube, i.e. pinning a course adds it to a "pinned" (__subscribed__) section of the side navigation. Future work might integrate a section of lectures by pinned courses on the start page all together.

**Comment by MSchreber** [comment]
Ja, danke. Sorry es war so versteckt, ich habe es nicht gesehen
