### ISSUE TITLE
Migration to new start page

### ISSUE THREAD

**Issue by MatthiasReumann** [joschahenningsen/TUM-Live#1038]
What follows is a list of TODOs and Gotchas for the migration to the new start page.

- [ ] Move current start page to `/old` or remove it altogether. 
    - [ ] 🧹 Check for any unused functions/methods/instance variables/etc. and remove them too. This probably is a lot of code.
- [ ] Permanent Redirect (either via Go or Fileserver configuration) to keep canonical links working.
    - [ ]  `/semester/2022/S` → `/?year=2022&term=S`
    - [ ] `/course/2022/S/LA2uDSMA0005` → `/?year=2022&term=S&slug=LA2uDS&view=3`
- [ ] Add canonical links to new start page's `<head>`

**Comment by joschahenningsen** [comment]
One more thing I noticed: When you are not logged in or not enrolled in any courses, the new start page shows nothing. In this case, it would be nice to treat all public courses kind of as if the user was enrolled in them, UI wise.
