### ISSUE TITLE
Uploaded video has no audio. 

### ISSUE THREAD

**Issue by TimOrtel** [joschahenningsen/TUM-Live#1041]
I uploaded a video but it does not come with any audio once uploaded. My local file has audio. 

This is the uploaded video: https://tum.live/w/artemisintro/33328

This is the output by ffprobe on my local file:

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'exp_quiz_part.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:03:38.16, start: 0.000000, bitrate: 248 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 518x1064 [SAR 1:1 DAR 37:76], 113 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: mp3 (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

Is there a ffmpeg command I can run to convert the file such that tumlive will have audio?

**Comment by joschahenningsen** [comment]
`ffmpeg -i in.mp4 -c:a aac -c:v libx264 out.mp4` should do the trick, weird that mp3/mp4a doesn't work… Can you share the original file with me on nextcloud.in.tum.de for debugging? My username is `hennings`

**Comment by joschahenningsen** [comment]
The issue might be that mp3 is nonfree and therefore possibly not bundled in the webplayer. I'll need to make sure to convert the audio stream of uploads to aac in the future.

**Comment by TimOrtel** [comment]
Thank you, with this command it works as expected.
