### ISSUE TITLE
Regarding video playback speed

### ISSUE THREAD

**Issue by saiyam3243** [joschahenningsen/TUM-Live#1063]
can you please add 2.25x playback speed, as sometimes 2x is a bit slow, and 2.5 is very fast? Or a feature like in vlc media player where the playback speed can be set manually or increased on the basis of 0.1.

**Comment by MatthiasReumann** [comment]
#1047 added the query parameter `rate` for the absolut customization of the playback speed. Once deployed you can adjust the rate via the URL as follows: `https://tum.live/w/ACoQC/29204?rate=3.0`
