### ISSUE TITLE
Watched/unwatched icons are not shown

### ISSUE THREAD

**Issue by ahmetsenturk** [joschahenningsen/TUM-Live#1089]
Under the course overview, where the lectures are listed, in the old version one could see the watching status with the icons next to the videos:
<img width="677" alt="Screenshot 2023-07-26 at 12 53 25" src="https://github.com/joschahenningsen/TUM-Live/assets/35606355/5d8d83e2-5975-44aa-9fc4-b938d30d9de1">

Currently, you can filter them- but the icons are gone:
<img width="1407" alt="Screenshot 2023-07-26 at 12 51 47" src="https://github.com/joschahenningsen/TUM-Live/assets/35606355/ce13c852-fef1-48f5-aa08-1995162d49c9">

I believe it would be really convenient to add those icons back 😊

**Comment by alexanderstephan** [comment]
I think the current behavior is that the blue bar at the bottom marks the watch state.
If you mark a video as watched, the bar should become fully blue, right?

**Comment by ahmetsenturk** [comment]
That is correct, thanks for pointing it out. Still, I feel like the other way was a little bit more intuitive, it might be just me though 😅

**Comment by MatthiasReumann** [comment]
We could add the eye symbol to the thumbnail though. 🤔
