### ISSUE TITLE
(old ui) Download button on course page not working

### ISSUE THREAD

**Issue by simon300000** [joschahenningsen/TUM-Live#1090]
**Describe the bug**
The download url returns 404, on the old course page

(on the individual page of VODs everything is fine)

the url `https://tum.live/api/download/27102/linalginfo/linalginfo-April-18-2023` is 404

which should be: `edge.live.rbg.tum.de/...`

**To Reproduce**
1. Go to https://tum.live/old/course/2023/S/linalginfo
2. click download
3. See 404

**Expected behavior**
start downloading video, or pop up selection panel for selecting combined/cam/pres like the new ui

**Screenshots**
<img width="193" alt="image" src="https://github.com/joschahenningsen/TUM-Live/assets/12656264/159b4fa9-fd54-48da-ae58-468e0caefc3f">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 17

**Comment by simon300000** [comment]
similar problem also on the new ui, (it didn't when I tested some times ago... I remember)
(should I create a new issue?)

go to https://tum.live/?year=2023&term=S&slug=linalginfo&view=3
click one of the download options

<img width="343" alt="image" src="https://github.com/joschahenningsen/TUM-Live/assets/12656264/75ed41c8-3ce6-4155-8f34-4d12e4384dc9">

it seems to be the json file result was missing the jwt token

<img width="850" alt="image" src="https://github.com/joschahenningsen/TUM-Live/assets/12656264/726dadd9-d270-449f-bd4b-c3afeaddda84">

return of the json `https://live.rbg.tum.de/api/courses/linalginfo/?year=2023&term=S`, download url without jwt token however

**Comment by joschahenningsen** [comment]
Thanks for the report, no need for a separate issue :)
