### ISSUE TITLE
Changing view button doesn't work correctly.

### ISSUE THREAD

**Issue by Spanthyx** [joschahenningsen/TUM-Live#1096]
**Describe the bug**
When pressing the change view button while watching a recording of a lecture, it doesn't show the view options. I can only see the bottom of the box with view options that would appear completely if the button worked. Only when I put the browser on 150% scale did it show the box entirely with all the options.

**To Reproduce**
1. Go on any recording on TUMLive
2. Press the change view button.

**Expected behavior**
Show the box with the different view options.

**Screenshots**
At 100% browser scaling:
<img width="300" alt="image" src="https://github.com/joschahenningsen/TUM-Live/assets/69044190/4af6448a-c756-45ac-8bc6-315e09e97e36">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.4.1 (c)
 - Browser: Arc (Chromium based browser)
 - Version 1.0.1 (40233)
Chromium Engine Version 115.0.5790.98

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MatthiasReumann** [comment]
Thanks for reporting! The issue is already known (#1093).
