### ISSUE TITLE
too much unnecessary information with new design

### ISSUE THREAD

**Issue by szmahdis** [joschahenningsen/TUM-Live#1104]
The thumbnail view take too much space and doesn't give any useful information to the user.
Every time i have to click on "More" to get to the lecture that i want to watch, which is waste of clicks and harder to navigate.
The previous version with list view was more compact and gave the user a nice overview of all the videos for each lecture.

**Comment by MatthiasReumann** [comment]
Thanks for the feedback! 

The `more` button will be gone after #1122 is merged. Sorry for that. I really don't know why I paginated the streams on the course page 😅 Furthermore, the streams will be once again be grouped by month for ease of navigation.
