### ISSUE TITLE
design flaws

### ISSUE THREAD

**Issue by de-arl** [joschahenningsen/TUM-Live#1105]
Big and bold fonts for unimportant information
badly readable pale and small styles for important information
bad page layout, composition is not well proportioned and looks unfinished
title of shows is to small
time is to big
to much white space, why not use it?

In total, I am not even sure wether it is supposed to look like this or wether it is not rendered correctly:
![ss_2023_0801-163935](https://github.com/joschahenningsen/TUM-Live/assets/25202540/d5133d4f-8f8f-4f57-87fb-ba69bbef3f63)

**Comment by joschahenningsen** [comment]
It's actually not rendered correctly, there should be thumbnails... What browser and device do you use? Are there any errors on the web console?

**Comment by de-arl** [comment]
I use qutebrowser on a laptop with default configuration, javascript and html5 cache enabled. No errors when running with --debug.
________________________________
Von: Joscha Henningsen ***@***.***>
Gesendet: Dienstag, 1. August 2023 18:19:08
An: joschahenningsen/TUM-Live
Cc: Andreas Laible; Author
Betreff: Re: [joschahenningsen/TUM-Live] design flaws (Issue #1105)


It's actually not rendered correctly, there should be thumbnails... What browser and device do you use? Are there any errors on the web console?

**Comment by MatthiasReumann** [comment]
Hey! Thanks for the issue. 
Unfortunately, TUM-Live only supports the most commonly used browsers, i.e., Chrome, Firefox, and Safari, due to time and labor efficiency. Therefore we kindly ask you to switch to one of these browsers when using TUM-Live.
