### ISSUE TITLE
Course page invisible due to wrong scrolling position

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#1107]
**Describe the bug**
When navigating to a course via "Show all my courses" view the course page is not visible for the course is not visible
without scrolling up for some courses.

**To Reproduce**
1. Go to the start page
2. Click on 'Show all my courses'
3. Scroll down at least one page (!)
4. Click on any course

**Expected behavior**
The course page content is at the top of the page.
It should be visible without any further actions by the user.

**Comment by MatthiasReumann** [comment]
Note: Firefox only bug
