### ISSUE TITLE
Settings to change date display format

### ISSUE THREAD

**Issue by cod-eric** [joschahenningsen/TUM-Live#1110]
**Is your feature request related to a problem? Please describe.**
I would enjoy having the option to change the way the date of lectures is presented, e.g. 12.7.2023 instead of 7/12/2023, or Wednesday, 12.7.23, etc.
Additionally, I think it would be great for the date to be a bit larger in the lecture overview for better visibility.

**Comment by MatthiasReumann** [comment]
Thanks for the issue! Once #1095 is merged, your browsers default language will be used to display dates with day names.
For example:
`en-US` Tuesday, 27/06/2023, 08:00
`de-DE` Dienstag, 27.06.2023, 08:00

Font will be bigger too!
