### ISSUE TITLE
New Design: "Profile picture" confusing

### ISSUE THREAD

**Issue by MariusAlbrecht** [joschahenningsen/TUM-Live#1112]
To me the "Profile Picture" in the top right suggests this actually being changeable somewhere. If that's not a planned feature then i would suggest using a more generic person/profile icon (e.g. similar to material design [Account Circle](https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/account_circle/default/account_circle_symbol.svg) or [Person](https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/person/default/person_symbol.svg), [Face](https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/face/default/face_symbol.svg) symbols)

**Comment by MatthiasReumann** [comment]
Thanks for the issue! Will be fixed in #1095 

Sorry for the inconvenience. 

![Screenshot 2023-08-08 at 12 08 09](https://github.com/joschahenningsen/TUM-Live/assets/29633518/74fddd74-6a9a-4bdd-af17-81b3b567899e)
