### ISSUE TITLE
Pinned courses are only visible in their semester

### ISSUE THREAD

**Issue by gkuznik** [joschahenningsen/TUM-Live#1116]
**Describe the bug**
Pinned courses only show up if you select the semester they're in.

**To Reproduce**
1. Pin course
2. Switch semester
3. Go to homepage (-> sidebar)
4. Pinned course is not visible

**Expected behavior**
Pinned course is always visible regardless of semester. This is makes the feature more useful.

**Comment by MatthiasReumann** [comment]
Thanks for the issue! Pinned courses will be visible regardless of the selected semester once #1095 is merged.
