### ISSUE TITLE
False Order of Videos

### ISSUE THREAD

**Issue by yasinmahan** [joschahenningsen/TUM-Live#1143]
**Describe the bug**

The Order buttons "Newest first" and  "Oldest first" dont work properly.
Oldest first  : shows the oldest video of the newest Month at first.
Newest first : shows the newest video of the oldest Month at first. 

**To Reproduce**
Sort the Videos by Oldest first or Newest first

**Expected behavior**
Oldest first  --> show the oldest video of the oldest Month at first.
Newest first --> show the newest video of the newest Month at first. 

**Screenshots**

Screenshots of a Summersemestercourse:

![image](https://github.com/TUM-Dev/gocast/assets/101710426/99d71d5f-a7ee-4e15-a9fd-6e5b7ffd8700)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 115.0.5790.173 (Offizieller Build) (64-Bit)

**Comment by MatthiasReumann** [comment]
Thanks for the issue! Should be fixed once #1145 is merged.
