### ISSUE TITLE
The date indicated on the video is false

### ISSUE THREAD

**Issue by lordaouy** [joschahenningsen/TUM-Live#1151]
**Describe the bug**
The date displayed on the video is incorrect. It shows a date that does not match the actual date the video was recorded or supposed to represent.

You will notice that the date on the L01 video is incorrect; part of it is from one month, while another part is from a different month, even though they should all come from the same day.

**To Reproduce**

1. Go to the [W2022 Patterns in Software Engineering (IN2081) course page](https://live.rbg.tum.de/?year=2022&term=W&view=3&slug=pse).
2. Notice that the date displayed on the video or in the video details is incorrect.

**Expected behavior**
The expected behavior is that the date associated with the video correctly reflects the actual date the video was recorded or is supposed to represent.

**Screenshots**
This is screenshot from [W2022 Patterns in Software Engineering (IN2081) course page](https://live.rbg.tum.de/?year=2022&term=W&view=3&slug=pse)
![image](https://github.com/TUM-Dev/gocast/assets/110788250/7264e8d5-ae0f-483e-8037-c38de1f652c8)
![image](https://github.com/TUM-Dev/gocast/assets/110788250/31426d05-933f-41b7-891b-f38a5e27af47)

**Desktop (please complete the following information):**
- OS:  Window 11
- Browser:  Google Chrome
- Version: Version 116.0.5845.141 (Official Build) (64-bit)

**Comment by joschahenningsen** [comment]
These are pre-recorded lectures, that were re-uploaded by a chair that selected these dates. I'd also like them to chose the actual dates when uploading their lectures but this is not a bug.
