### ISSUE TITLE
0 viewers in a stream with multiple hundreds https://live.rbg.tum.de/w/vkmi/35283?dvr=&t=925

### ISSUE THREAD

**Issue by Wladefant** [joschahenningsen/TUM-Live#1160]
0 viewers are shown on tum live (https://live.rbg.tum.de/w/vkmi/35283?dvr=&t=925) even the stream definitely has at least hundred people.

![image](https://github.com/TUM-Dev/gocast/assets/79611093/f014e5e9-1723-44f4-9a53-8f968307ed99)

P. S.: This is the mathe vorkurs

Even the professor (host) has the same number of viewers

**Comment by Wladefant** [comment]
This seems to be solved nowˋ?

**Comment by joschahenningsen** [comment]
Yes, this should be resolved.
