### ISSUE TITLE
Old speed ui looks rather strange 

### ISSUE THREAD

**Issue by Wladefant** [joschahenningsen/TUM-Live#1162]
I like the UI very much looks modern to me and matches the tum theme. But somehow you missed the playback speed ui?
I am right now in the beta player 
![image](https://github.com/TUM-Dev/gocast/assets/79611093/9540776d-e88f-4ba7-803b-3c0afaad03b8)
The ui looks rather strange

**Comment by karjo24** [comment]
Duplicate of #1165 (+ outdated screenshot?)
