### ISSUE TITLE
Wrong Order when sorted by Newest or Oldest if the video are posted in different years 

### ISSUE THREAD

**Issue by leonwind** [joschahenningsen/TUM-Live#1169]
**Describe the bug**
The order of the videos is wrong when one sorts them, and some videos are posted end of a year (e.g., October - December) and beginning of a new year (January - February)
Meaning: Sorted by newest places October - December 2022 ahead of January - February 2023, other way around for sort by oldest.

**To Reproduce**
1. Go to `any course`
2. Click on 'Sort by Oldest / Newest`
3. See error

**Expected behavior**
A correctly sorted list of the videos

**Screenshots**
![oldest-first-wrong-order](https://github.com/TUM-Dev/gocast/assets/15003401/4ebe8ca7-63f0-4482-9a12-edf30050943e)
![newest-first-wrong-order](https://github.com/TUM-Dev/gocast/assets/15003401/b1062989-1cb8-4d04-a4d1-f8e16cc6d0ae)

**Desktop (please complete the following information):**
 - OS: NixOs
 - Browser Google Chrome

**Comment by MariusAlbrecht** [comment]
related #1143 #1149

**Comment by alexanderstephan** [comment]
Thanks for the nice issue. This has already been addressed in https://github.com/TUM-Dev/gocast/pull/1150. It is just not deployed yet, sorry for that.

**Comment by joschahenningsen** [comment]
The deployment delay is on me, sorry!

**Comment by joschahenningsen** [comment]
Should be good now :+1:
