### ISSUE TITLE
Seeking 15 seconds is too long 

### ISSUE THREAD

**Issue by brigit245** [joschahenningsen/TUM-Live#1171]
The seeking currently is set to 15 seconds which in normal speed is too long. Oftentimes, I want to go back for a second or two to better hear or understand what the professor said but instead I can only go back 15 seconds and by the time I reach the point in the video that I wanted to replay I am either distracted or I have to do it multiple times. Seeking using the progress bar is even worse most of the time. 

Ideally, there could be a setting to set the preferred seek time for each user, but even reducing it to 5-7 seconds is good.

**Comment by joschahenningsen** [comment]
Agreed, this could be a userSetting.
