### ISSUE TITLE
session zx6r

### ISSUE THREAD

**Issue by Filip427** [joschahenningsen/TUM-Live#1174]
I'm on tum live trying2watch a broadcast.
I click on play and it doesn't work.
the session already began, even though there says no active stream and stream is due. 

https://github.com/TUM-Dev/gocast/assets/110301238/329728f4-9748-4f52-be06-aef4cf2f0d80

 16 minutes ago

The lecture is already running for 10 minutes

**Comment by joschahenningsen** [comment]
Please refresh the page.

**Comment by joschahenningsen** [comment]
This is due to self-streamers sometimes starting at another time than scheduled. Therefore, the "starts at/stream is due" message might sometimes not be accurate.
