### ISSUE TITLE
Course setting cannot be saved

### ISSUE THREAD

**Issue by bernhard0309** [joschahenningsen/TUM-Live#1178]
**Describe the bug**
"Save Settings" Button for Course Settings does not work
**To Reproduce**
1. Go to 'Settings"
2. Change Visibility of this course 
3. Click "Save Settings"
4. Reload page 
5. -> Visibility of this course is not changed 

**Expected behavior**
Save new selected visibility of course

**Desktop (please complete the following information):**
Windows 10, Edge or Firefox

**Comment by alexanderstephan** [comment]
Seems to be due to the rename of a function:
![image](https://github.com/TUM-Dev/gocast/assets/30267166/4bc317b3-3240-4158-a389-f1d19e0e6091)

**Comment by alexanderstephan** [comment]
Cannot reproduce locally with latest `dev`.

**Comment by joschahenningsen** [comment]
ee92bd6685851090ef2a5660b53ecdf87eb6c5ba is currently deployed. Maybe this issue only affects lectures with chat enabled?

**Comment by joschahenningsen** [comment]
@mono424 was this possibly introduced in #1137?

**Comment by mono424** [comment]
Could be, I tested again with the new Settings PRs, can we merge? Pretty sure this should fix it already :)

**Comment by joschahenningsen** [comment]
#1156?
