### ISSUE TITLE
More replay/playback speed options

### ISSUE THREAD

**Issue by schustobias** [joschahenningsen/TUM-Live#1182]
I personally would like to have a slider instead of the current options for speed regarding replay as sometimes 1 is to little and 1.25 to great. In such cases (and probably also other cases) it would be beneficial to be able to adjust the speed more precisely maybe with an increment of 0.05 / 5% or even 0.01 / 1% (1% admittedly might probably be a bit too small, but that would result in complete control over the playback speed). Alternatively I would suggest that the increment could be set somewhere by the user or that you could simply type a value between maybe 0.01 and 3 or maybe even 4 into a input field changing the playback speed this way. In conclusion I would still opt for the first option namely the slider as it appears to me as the best option for this.

**Comment by MariusAlbrecht** [comment]
#1047 added a url parameter that basically implements this but didn't go along with UI changes that would reasonably enable the user to use that parameter
I personally would like the ability to just add playback rates in the settings
