### ISSUE TITLE
Security policy not available

### ISSUE THREAD

**Issue by schustobias** [joschahenningsen/TUM-Live#1183]
The links https://github.com/TUM-Dev/gocast/security/policy#security-policy 
and
https://github.com/TUM-Dev/gocast/security/policy#reporting-a-vulnerability
at
https://github.com/TUM-Dev/gocast/security/policy
do not lead to anything and nothing regarding the security policy is either visible or available.

**Comment by MariusAlbrecht** [comment]
for me it says "If you found security issues, please send a mail to live-at- rbg.tum.de :)"

**Comment by CommanderStorm** [comment]
Closing as not reproducible
