### ISSUE TITLE
Setting to automatically "Skip" after opening stream

### ISSUE THREAD

**Issue by MariusAlbrecht** [joschahenningsen/TUM-Live#1188]
**Describe the solution you'd like**
I would like the option to set a default behavior for streams upon opening, where they automatically skip the initial inactive period and start at the next active segment.

**Describe alternatives you've considered**
Manually pressing the button in the playback controls each time I open a stream is an alternative. However, an automated setting would provide a more convenient and seamless experience. Also avoids the extra loading time of first loading at 00:00 and then loading again after skipping

**Comment by Mjaethers** [comment]
This seems doable, I have started working on this

**Comment by MariusAlbrecht** [comment]
nice! Seems like a good opportunity to use the user settings
