### ISSUE TITLE
Add location to "Scheduled" lectures on course page

### ISSUE THREAD

**Issue by MatthiasReumann** [joschahenningsen/TUM-Live#1193]
**Describe the solution you'd like**
Add a clickable link to the location (e.g. HS2) of "Scheduled" lectures on the course page referring to NavigaTUM. 

![Screenshot 2023-10-17 at 09 51 09](https://github.com/TUM-Dev/gocast/assets/29633518/b8de3042-f0c5-47f3-94ff-1bdea8de7520)

**Comment by mohanadkandil** [comment]
Do normally classes provide the location with the stream ? cause I have some classes with no info about location (just time). 
Indeed, I can start working on this

**Comment by joschahenningsen** [comment]
Classes without locations associated to them are usually self streams. (using OBS, etc.)

**Comment by KemalKrKX** [comment]
I would like to work on this issue, if no one actively is.
