### ISSUE TITLE
Camera window enlargement when beamer is turned off

### ISSUE THREAD

**Issue by Moritzslz** [joschahenningsen/TUM-Live#1195]
Today I had the first lecture where the professor used the blackboard instead of Goodnotes etc. When watching the recording of the lecture I encountered severe difficulties in reading the content of the blackboard since the window of the camera is so small.

**Describe the solution you'd like**
As soon as the beamer is turned off (black screen on recording) the camera window should be automatically enlarged to fit the size of the Iframe.

**Comment by CommanderStorm** [comment]
@hmelder Should I move this Issue to https://github.com/TUM-Dev/TUMmp

**Comment by joschahenningsen** [comment]
@Moritzslz can you please share the link to the lecture?

**Comment by joschahenningsen** [comment]
I assume there is a camera only recording of the lecture. But it might not be fully transcoded yet.

**Comment by Moritzslz** [comment]
@joschahenningsen https://tum.live/w/anainfo/37196; I did not know that camera-only recordings are provided on tum.live. Where would I be able to find those?

**Comment by joschahenningsen** [comment]
Under the player there is a button to switch the view. The camera version is this one: https://tum.live/w/anainfo/37196/CAM

**Comment by hmelder** [comment]
> @hmelder Should I move this Issue to https://github.com/TUM-Dev/TUMmp

it would require a lot of work to dynamically detect this behaviour on this level, as it involves dynamic composition based on the state of the capture device. 

And we are using a SMP in this lecture hall.

I would suggest a preset in TUM-Live for changing the default view, if the presenter intends to only use the camera source. On the other hand, this would make switching during recording difficult.

What do you think @joschahenningsen ?

**Comment by joschahenningsen** [comment]
This is already possible, the presenter didn't set this though. @hmelder
