### ISSUE TITLE
My Course Does Not Appear

### ISSUE THREAD

**Issue by izmirnilsu** [joschahenningsen/TUM-Live#1197]
Hello,
My course Introduction to Programming does not appear on https://live.rbg.tum.de/. I cannot access the live class. Could you please help me? Thank you very much!

**Comment by joschahenningsen** [comment]
Are you enrolled to the course in tum online? If yes, when did you enrol?

**Comment by joschahenningsen** [comment]
Here's how to do it in firefox:


https://github.com/TUM-Dev/gocast/assets/44805696/2e228e65-ff0d-4525-9ca5-5b988075fbe2

**Comment by izmirnilsu** [comment]
I enrolled 1.5 weeks ago. It appears now, thank you very much!
