### ISSUE TITLE
Popup chat does not update

### ISSUE THREAD

**Issue by JosefSchoenberger** [joschahenningsen/TUM-Live#1199]
**Describe the bug**
The popup chat does not receive any updates. Most notably, it does not show any new messages but remains frozen in time.

**To Reproduce**
1. Go to an active chat
2. Open the popup chat
3. Enter a new message on a separate window
4. See that the message has appeared in the chat next to the stream/video window, but not in the popup.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 118.0.2 (64-Bit)

**Additional context**
Tested during the livestream of GBS (https://live.rbg.tum.de/w/GBS/36950).

**Comment by MakisH** [comment]
I had exactly the same issue with my lecture today, using Ubuntu 22.04 and Firefox 120. This was a bit embarrassing, as students were asking questions, but I thought there were none. :grimacing:
