### ISSUE TITLE
Combined presentation and camera view

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#120]
In addition to the “comb-view” video there should be an option to view both camera and presentation videos side by side and modify their sizes.
Important gotchas: We need to make sure the videos are synchronized and only one of them should be un-muteable at the same time.

**Comment by ata-keskin** [comment]
I would like to implement this functionality. I will post an update once I start working on it.

**Comment by alexanderstephan** [comment]
Awesome! :)

**Comment by A-Sam** [comment]
Does this issue include the "dragability of the camera"? If camera is set on another layer in front of the presentation, then we can make the background is presentation mode and put camera in front of it, then the user can pan it around if it covers part of the presentation slides. This will solve #418 actually

**Comment by ata-keskin** [comment]
It doesn't actually, but it makes sense to implement that as part of this issue. As you've said it would solve all of the problems. If we can implement a "Canvas" where we have layers of video data that can be dragged around and resized (like in GIMP or Photoshop) this would solve a lot of the issues. First and foremost, this issue and #418 but also #226 once enough progress has been made. For starters we can assume that there are 3 streams and work on this issue that way, and then generalize this to n streams which will be easy to do given we have a "layer view system" that works. I hope it is clear what I mean by this.
