### ISSUE TITLE
No compatible source was found for this media.

### ISSUE THREAD

**Issue by izmirnilsu** [joschahenningsen/TUM-Live#1200]
For Introduction to Programming course, I cannot play certain recorded lectures as it gives the error "No compatible source was found for this media". For another video, I can see the voices but all I see is a black screen, so the video isn't loaded with the visuals. Could you please help me? Thank you very much!

**Comment by joschahenningsen** [comment]
Working on it.

**Comment by izmirnilsu** [comment]
Now it can be viewed. Thank you very much for your work!
