### ISSUE TITLE
Chat Does Not Support Pasting

### ISSUE THREAD

**Issue by tobiasjungmann** [joschahenningsen/TUM-Live#1208]
# Problem
Currently it is only possible to copy test from the chat somewhere else, but it is not possible to paste a message in the editor and send it successfully. The text does appear in the editor but is gone once the message is send. I am using firefox.

# Steps to reproduce
1. Go to stream/VOD with an active chat
2. Paste a message
3. Send message
4. Notice that the message never appeared

**Comment by barisgul15** [comment]
Hi, did this problem occurred while using popup chat? I tried the reproduce the problem but everything worked fine on my side. Popup chat had some problems sending all kind of messages when this issue is created, could that issue be related about that?

**Comment by barisgul15** [comment]
I tested this bug again and did not encounter such a problem. Like I have written, I think that might have happened because of the popup chat issue #1199. This has been fixed and copy-paste test was made on both popup and normal chat on the course page and both worked fine.
