### ISSUE TITLE
Playback using link with t=0 does not work

### ISSUE THREAD

**Issue by chris246** [joschahenningsen/TUM-Live#1214]
**Describe the bug**
Video URLs can include a time parameter from which the video will start, e.g. https://live.rbg.tum.de/w/foo/123456?t=42  
Setting `t=0` does not work but instead resumes the video from the previous playback position.

Not sure if this is intended though.

**To Reproduce**
1. Open a video
2. Use a time code link for accessing this video.
    * t>0 works
    * t=0 continues the video from the last playback position instead of playing the video from the beginning.

**Expected behavior**
Start the video at t=0

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 118.0.2

**Comment by YiranDuan721** [comment]
I am trying to solve the problem. Alternatively, argument "t=-1" should set the starting time at 00:00, does it?
