### ISSUE TITLE
Rechnerarchitektur Zentralübung 03.11.2023

### ISSUE THREAD

**Issue by MAyssa7** [joschahenningsen/TUM-Live#1228]
Hi,
i want to report a problem in the Stream of the Session Zentralübung of Rechnerarchitektur 03.11.2023 . 
Can you please fix this Bug as soon as possible 
Thank you !

**Comment by CommanderStorm** [comment]
What problem would you like to report?
Note that without good bug reports, debugging is way harder

**Comment by YiranDuan721** [comment]
Hello! Friendly reminder: do you know that there is a button on the website for reporting problems regarding technical problems with streaming, recording, etc? It has an exclamation mark on it:
<img src="https://github.com/TUM-Dev/gocast/assets/78721605/adea3048-536c-4b74-83e3-21d70ec656ad" width="30%"/>

I'm not sure about the issue during streaming, but I checked the recording of this session and I think everything's in order.
