### ISSUE TITLE
show watch progress in playlist view

### ISSUE THREAD

**Issue by MariusAlbrecht** [joschahenningsen/TUM-Live#1248]
**Is your feature request related to a problem? Please describe.**
In the normal course view (`&view=3`) a progress bar is shown at the bottom of a thumbnail. This makes for a good indicator of watch progress. However when opening the playlist in the normal view of a stream (`/w/<course>/<id>`) those progress bars are no longer shown.
This makes it hard to tell which recordings have been watched (and to what degree)

**Describe the solution you'd like**
Show the same progress bars there as well.
alternatively some sort of indicator whether the recording has been watched would solve my issue as well. (would create the problem if deciding what 'watched' specifically means and probably isn't much easier to implement anyways)

**Describe alternatives you've considered**
open streams in a new tab and hope progress is "restored". This is very cumbersome and doesn't work reliably

**Additional context**
may also be a bug?
Firefox 119 on Ubuntu 22

**Comment by YiranDuan721** [comment]
Thanks for the issue! I don't think this is a bug -- playlist in the watch page and streams of a course in the home page are implemented very differently, the items are based on different data models. I agree that it would be great if the progress bar can also be shown in the playlist, but I think this enhancement is not particularly urgent.

**Comment by MariusAlbrecht** [comment]
It certainly is not urgent, yes.
~~Maybe a sort of 'watched' indicator would be possible?~~
edit: Nvm I'll add that to the issue in more detail

**Comment by Mjaethers** [comment]
@meandaD are you currently working on this? If not I might have a crack at it

**Comment by YiranDuan721** [comment]
> @meandaD are you currently working on this? If not I might have a crack at it

Hi! No, I'm not. Good luck with the work!
