### ISSUE TITLE
Video and Audio out of sync

### ISSUE THREAD

**Issue by MariusAlbrecht** [joschahenningsen/TUM-Live#1254]
**Describe the bug**
in this recording:
https://live.rbg.tum.de/w/anainfo/37210
video and audio are quite a lot out of sync (about 12 real seconds)

**To Reproduce**
1. Go to https://live.rbg.tum.de/w/anainfo/37210
2. Most noticeable with  the sound of chalk on the blackboard
( more specific example: starts writing at [0:44:34](https://live.rbg.tum.de/w/anainfo/37210?t=2674) but sound only comes in at [0:44:46](https://live.rbg.tum.de/w/anainfo/37210?t=2686) )

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LST
 - Both on Firefox 120 and (real and ungoogled) chromium 119

**Comment by YiranDuan721** [comment]
For this VoD I've uploaded [a synchronised version](https://live.rbg.tum.de/w/anainfo/41741).
Since this problem doesn't happen frequently, I think we can handle them seperately whenever it occurs...

**Comment by YiranDuan721** [comment]
But I can see that the original one is good now, it's probably already fixed before I uploaded the new one.
Curiously, the two videos (original one and synchronised one) for VL7 look also the same...
