### ISSUE TITLE
Share dialog should be quittable with 'esc'

### ISSUE THREAD

**Issue by MariusAlbrecht** [joschahenningsen/TUM-Live#1255]
**Is your feature request related to a problem? Please describe.**
only quittable by clicking the 'x' or outside of the popup. This makes mouse action neccesary and feels unnatural (for me. I basically click 'esc', realise it doesnt work and then use my mouse)

**Describe the solution you'd like**
also make 'esc' close the popup

**Comment by barisgul15** [comment]
I just implemented this, because it also makes sense for me, but if you click outside anywhere on the tab on share dialog, it would also close the popup.

**Comment by MariusAlbrecht** [comment]
I personally think that makes sense.
