### ISSUE TITLE
Incorrect offset of the replay bar after switching to fullscreen mode in Splitview mode

### ISSUE THREAD

**Issue by A-Sam** [joschahenningsen/TUM-Live#1284]
**Describe the bug**
In split view mode, when i switch between fullscreen and minimized-screen the replay bar is skewed and is rendered with incorrect offset

**To Reproduce**
1. Go to 'Any Stream'
2. Click on 'Splitview'
3. Move the vertical bar that adjusts the size of the Presentation and Livestream view sizes a little bit to right or left.
4. Switch to Fullscreen.
5. You will see the replay bar has an incorrect offset and half of it is not visible.

**Expected behavior**
The replay bar should be centered correctly.

**Screenshots**
![image](https://github.com/TUM-Dev/gocast/assets/11005214/522b2e76-6eca-4b00-ae55-9cc5ce178dce)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Brave
 - Version 1.61

**Additional context**
To fix it, I have to adjust the size of any view again:
![image](https://github.com/TUM-Dev/gocast/assets/11005214/7ffaee04-1edc-4240-9fcc-18163723eafd)

**Comment by SebiWrn** [comment]
Thank you for this issue. This issue will be fixed in #1291.
