### ISSUE TITLE
EIDI Vorlesung 20.12.2023 

### ISSUE THREAD

**Issue by MAyssa7** [joschahenningsen/TUM-Live#1290]
the Eidi video record lecture 20.12.2023 doesn't work effectively! 
<img width="632" alt="Capture d'écran 2024-01-07 183122" src="https://github.com/TUM-Dev/gocast/assets/134854720/a90d06a0-995f-4259-857b-fec535ce05fd">

**Comment by YiranDuan721** [comment]
According to [https://live.rbg.tum.de/w/eidi/36122?t=990](https://live.rbg.tum.de/w/eidi/36122?t=990), there was no EIDI VL on 20.12.2023 ;)
Still, the camera-only and presentation-only view works.
