### ISSUE TITLE
eidi vorlesung 08.01.2024

### ISSUE THREAD

**Issue by MAyssa7** [joschahenningsen/TUM-Live#1299]
it doesn't work!

**Comment by YiranDuan721** [comment]
Currently there's no combined view available, specific problems are being identified. Please switch to split view, presentation view or camera view according to your needs and preferences. You can do that from the switch-view button:
![image](https://github.com/TUM-Dev/gocast/assets/78721605/1ac307b4-1909-4943-af0e-2a3d5bfec26f)
<img width=50% src="https://github.com/TUM-Dev/gocast/assets/78721605/c12cc6f0-8a58-4c8b-9acc-647041713d62">
