### ISSUE TITLE
Distinguish between available and unavailable views on the watch page

### ISSUE THREAD

**Issue by YiranDuan721** [joschahenningsen/TUM-Live#1311]
**Is your feature request related to a problem? Please describe.**
Sometimes, for various reasons, only some of the views of a lecture may be available for viewing. Especially in recent times, some lectures do not have a combined view, however, the default selection of combined view on the watch page can be misinterpreted to mean that there is no video available for this lecture. I would like to see a way to differentiate between the available and unavailable views on the watch page.

**Describe the solution you'd like**
1. Gray out unavailable views in the views selection list, and also disable the corresponding button: 
<div align="center">
<img width=30% src="https://github.com/TUM-Dev/gocast/assets/78721605/a11ff8ef-c795-430e-a0f9-d457419a2144">
</div>

2. When loading the watch page, load the first available view according to the following priorities:
    1. Combined view
    2. Split view
    3. Presentation-only view
    4. Camera-only view

**Comment by joschahenningsen** [comment]
Unavailable views (ie. stream url for that view does not exist in db) are not displayed here: ![Image](https://github.com/user-attachments/assets/f09d0738-0924-46df-a401-25cba2366f0f)

If they are displayed but don't load, there is some other issue.
