### ISSUE TITLE
 "watched" state is not being determined and set automatically

### ISSUE THREAD

**Issue by MariusAlbrecht** [joschahenningsen/TUM-Live#1312]
**Describe the bug**
in `view=3` the sorting option "Hide watched" does nothing for me. It neither hides 100% watched vods (according to the progress bar), nor does it hide almost fully watched vods (the actual lecture normally ends a few minutes before the vod ends)

**To Reproduce**
1. Go to any lecture with vods
2. Watch one of the vods
3. click "Hide watched"
4. see nothing

**Screenshots**
![screencast](https://github.com/TUM-Dev/gocast/assets/64852250/4ad753d9-ebf4-4ad2-8fbb-2ab6b7bc28af)
[gbs 23w](https://live.rbg.tum.de/?year=2023&term=W&slug=GBS&view=3)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Browser: Firefox 121

**Comment by MariusAlbrecht** [comment]
I just saw theres a "mark watched" context option for each vod. Does this mean the "watched" state is not being determined and set automatically?

**Comment by SebiWrn** [comment]
Yes, I think that's the problem, I'll edit the Issue so it says: ' "watched" state is not being determined and set automatically'

**Comment by YiranDuan721** [comment]
I think the 'watched' state can only be determined automatically reasonablely, when this problem is solved: #1186, for example through #1206, which is planned to be covered in the development of the runners as substitution for the current workers
