### ISSUE TITLE
Add real "Last Lecture" date to courses under "My Courses" and rename "Last Lecture" to "Next lecture"

### ISSUE THREAD

**Issue by bastidmn** [joschahenningsen/TUM-Live#1321]
**Is your feature request related to a problem? Please describe.**
When logging into the website, the section "My Courses" always displays "Next lecture" under the courses, but with the date of the last lecture.

**Describe the solution you'd like**
It would be nice to keep the "Next lecture" line, but display the actual date of the next lecture planned in the system. Also, adding a line showing the "Last Lecture" information already present.

**Describe alternatives you've considered**
Alternatively, the "Most recent lecture" link could be integrated into "Last Lecture".
Additionally, a monospace font could be used to align "Next Lecture" and "Last lecture" vertically and increase readability (fixed 2 characters for day and month would also be great : ))

**Additional context**
Example picture of the desired functionality:
![image](https://github.com/TUM-Dev/gocast/assets/63459746/51aa29b9-a207-44f4-91be-f228c540f4d9)

**Comment by YiranDuan721** [comment]
Wow thanks for the issue, I actually have never noticed that the "next lecture" is displayed with incorrect date.
Of these two I prefer the former one. Or, not adding the date of the last lecture. I as a user would like this list to be concise. (Just personal thought.)

> #### Describe alternatives you've considered
> Alternatively, the "Most recent lecture" link could be integrated into "Last Lecture".
Additionally, a monospace font could be used to align "Next Lecture" and "Last lecture" vertically and increase readability (fixed 2 characters for day and month would also be great : ))
