### ISSUE TITLE
Toggle Light/Dark Mode Based on System Theme

### ISSUE THREAD

**Issue by just-max** [joschahenningsen/TUM-Live#133]
Many websites and apps [1] have added the ability to not only switch manually between a dark and light theme, but also to adapt automatically to the system theme. TUM-Live should add this as an option.

**Solution**
The existing theme-switcher button should be extended to cycle between light mode, dark mode and auto mode (follow system theme). In light or dark mode, the behaviour should be as before. In auto mode, TUM-Live should check the preferred theme upon loading and then listen for updates, updating the displayed theme as needed.

The following issue describes adding the same feature to VSCode, the link points specifically to a comment suggesting a clean way of implementing theme preference: https://github.com/microsoft/vscode/issues/61519#issuecomment-558738593. The solution bases off of using `window.matchMedia('(prefers-color-scheme: dark)')`

**More info**
- Chromium-based snap apps, eg. Google Chrome on Ubuntu, don't update `prefers-color-scheme` properly (see https://bugs.chromium.org/p/chromium/issues/detail?id=998903). Automatic switching would not work in this case.

- Documentation/examples: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Testing_media_queries

**Implementation**
I've gone ahead and implemented this, PR incoming.

***
[1] examples: github, VSCode

**Comment by joschahenningsen** [comment]
Hi :wave:!

> Chromium-based snap apps, eg. Google Chrome on Ubuntu, don't update prefers-color-scheme properly (see https://bugs.chromium.org/p/chromium/issues/detail?id=998903). Automatic switching would not work in this case.

That's why I decided not to go for "auto" by default 

> I've gone ahead and implemented this, PR incoming. 

Amazing!

Honestly I'm really not a fan of the current light mode (the theming could use some love in general but there was not too much time for this lately) :smile:

**Comment by just-max** [comment]
:wave: 
> That's why I decided not to go for "auto" by default

I've done the same

On the topic of themes: the yellow-on-white notice about the old version of the site offers somewhat subpar readability :sweat_smile:
