### ISSUE TITLE
Redirect to tum.live as main domain

### ISSUE THREAD

**Issue by kordianbruck** [joschahenningsen/TUM-Live#1331]
It'd be nice, if tum.live would be the primary domain. Can we setup a redirect, so live.rbg.tum.de instead redirects to tum.live?

**Comment by joschahenningsen** [comment]
@AndreasPaul any objections?

**Comment by AndreasPaul** [comment]
Hallo,

Also ich persönlich hab da nichts dagegen, ich würde aber erwarten, daß
Andere den Dienst lieber unter der tum.de Domäne sehen würden damit auch
allen klar ist, daß das ein Service der TUM ist.

So ähnlich wie nav.tum.de ja auch unter der tum.de Domäne läuft.

Stefan Schwalb wäre da wohl der richtige Entscheider, in der Hierarchie
weiter nach oben wären es dann Anton Frank und schließlich Alex Braun.


  Beste Grüße,

    Andreas Paul



On Wed, Feb 28, 2024 at 12:05:09PM -0800, Joscha Henningsen wrote:
> @AndreasPaul any objections?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/TUM-Dev/gocast/issues/1331#issuecomment-1969777260
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

-- 
Dr. Andreas Paul

Technische Universität München
School of Computation, Information and Technology

Boltzmannstr. 3
85748 Garching bei München

Tel. : +49 89 289 18539
eMail: ***@***.***

**Comment by kordianbruck** [comment]
Jou, damit wir unter der direkten TUM Domain laufen ist wesentlich mehr Arbeit notwendig. Das war für nav.tum.de sehr viel Aufwand. Machbar, aber ich glaub da gibt es noch viele weitere Einflussfaktoren, welche ich jetzt lieber nicht aufwärme.
