### ISSUE TITLE
Can't access video

### ISSUE THREAD

**Issue by rafat2205** [joschahenningsen/TUM-Live#1332]
# Before you file this issue:
Awesome, bug reports are among the most important things a community can do for a project. **However**, they shouldn't put said community at risk. If the bug you found might lead to 
- Exposure of personal data
- Unauthorized modification of personal data
- Unauthoritzed streaming
- Unauthorized access to protected streams
or anything similar, please report your issue via mail (mailto:joscha.henningsen@tum.de)[joscha.henningsen@tum.de]

**Describe the bug**
Video does not load for 19/12/2023, 16/01/2024, 23/01/2024 of [Fundamental Algorithms (CSE) (IN2157)](https://live.rbg.tum.de/course/2023/W/FundAlg)

**To Reproduce**
1. Go to (https://live.rbg.tum.de/course/2023/W/FundAlg)
2. Click on the lectures of 19/12/2023, 16/01/2024, 23/01/2024

**Expected behavior**
I think the video is corrupted, I complained before but did not get a response. Can you please check if a reupload solves the issue.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser safari

**Smartphone (please complete the following information):**

**Additional context**

**Comment by YiranDuan721** [comment]
Hi,
this is a very known issue, the team is trying to solve it. Sorry for the inconvenience. As for the three lectures you've listed, the camera view, presentation view and split view work well for me. I hope they can make up for the combined view for you.

**Comment by rafat2205** [comment]
Hi,

For me the video doesn't load at all. I don't need the combined view. I
just need the presentation view. Can you please guide me about how to turn
on the presentation view only?

Thank you.

**Comment by YiranDuan721** [comment]
I hope this can help you: [https://github.com/TUM-Dev/gocast/issues/1299#issuecomment-1882560593](https://github.com/TUM-Dev/gocast/issues/1299#issuecomment-1882560593)
