### ISSUE TITLE
Be more format agnostic 

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#1336]
In order to be successful, this website should be more accessible to people who are not computer scientists. Therefore, it should not matter which kind of video someone Uploads. gocast should always try its best to convert input to a format that is recognised by popular browsers.

**Comment by KemalKrKX** [comment]
@joschahenningsen Do you mean for example converting a lecture.avi file into lecture.mp4 or some other format? Just want to be sure what is the desired outcome here.

**Comment by joschahenningsen** [comment]
In essence yes, I'm more concerned about Codec than Container though. It shouldn't matter, which Codec the input video and audio are, gocast should try its best to always present the stream and vod in h.264, aac.

**Comment by joschahenningsen** [comment]
I checked the code and it seems we already check the video codec. What we still need to check is that the audio codec is aac.
