### ISSUE TITLE
The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by mariusgritl** [joschahenningsen/TUM-Live#1343]
I use the live.rbg platform for recording a lecture. Today (March 28, from 10AM to 12:15PM) I gave a lecture in MI lecture hall 2. The livestream works well but now the students are not be able to watch the recording. Downloads are also not possible.
I refer to the course https://live.rbg.tum.de/course/2023/W/laph23w

Thank you!

**Comment by SebiWrn** [comment]
I'll close this issue because the VOD works now.
