### ISSUE TITLE
The media could not be loaded…

### ISSUE THREAD

**Issue by mariusgritl** [joschahenningsen/TUM-Live#1344]
Hi 

I am teaching a course in FMI HS2 this semester, and unfortunately, the recording of the first lecture did not work. I am referring to the course https://live.rbg.tum.de/course/2024/S/pdephys24s

Last semester, I also taught a course in HS2, and the same problem occurred. Are there any issues specific to this lecture hall?

Thank you very much!
Marius

**Comment by SebiWrn** [comment]
Issue should be fixed now. Normally FMI HS2 shouldn't be a problem but we'll have a look into it. Thank you!
