### ISSUE TITLE
Grundlagen: Algorithmen und Datenstrukturen (IN0007) 17.04.2024 recording

### ISSUE THREAD

**Issue by gamebeaker** [joschahenningsen/TUM-Live#1349]
**Describe the bug**
If i want to watch the recording i get this message:
You don't have permissions to access this stream. Please make sure to use the correct login.

**To Reproduce**
1. Go to [https://tum.live/w/GAuD/45986](https://tum.live/w/GAuD/45986)
2. See error

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser firefox
 - Version: 125.0.1
 
**Additional context**
I am loged in and can watch the other recording but not this one.

**Comment by SebiWrn** [comment]
Can you please try it again, should be fixed now

**Comment by gamebeaker** [comment]
@SebiWrn yes it works now.
Thanks for your work.
