### ISSUE TITLE
skippable region wrongly recognized

### ISSUE THREAD

**Issue by MariusAlbrecht** [joschahenningsen/TUM-Live#1352]
**Describe the bug**
a skippable region is being recognized when there isn't actually one

**To Reproduce**
1. Go to https://live.rbg.tum.de/w/DW/43752?t=5888
2. skip available
3. don't skip
4. see error

**Expected behavior**
don't offer a skip / don't recognize region as skippable

**Desktop (please complete the following information):**
 - OS: ubuntu 23.10
 - Browser: Firefox 125.0 snap

**Additional context**
should probably be fixed by #1329, another point of reference doesn't hurt tho

**Comment by SebiWrn** [comment]
This happens so rarely that it's not really necessary at the moment to fix this issue by tweaking the ffmpeg parameters as this would require a lot of time.
