### ISSUE TITLE
GAD Lecture 30.4. not loading 

### ISSUE THREAD

**Issue by Schansiate** [joschahenningsen/TUM-Live#1353]
# Before you file this issue:
Awesome, bug reports are among the most important things a community can do for a project. **However**, they shouldn't put said community at risk. If the bug you found might lead to 
- Exposure of personal data
- Unauthorized modification of personal data
- Unauthoritzed streaming
- Unauthorized access to protected streams
or anything similar, please report your issue via mail (mailto:joscha.henningsen@tum.de)[joscha.henningsen@tum.de]

**Describe the bug**
Gad Lecture of April 30.2024 is nor loading 
**To Reproduce**
1. Go to Grundlagen: Algorithmen und Datenstrukturen (IN0007) and lecture of Tuesday 
2. Click on play 
3. See error 'The media could not be loaded...'

**Expected behavior**
The VOD of the lecture playing.

**Screenshots**
<img width="1437" alt="Screenshot 2024-05-01 at 11 50 03" src="https://github.com/TUM-Dev/gocast/assets/143003293/663b9e44-2ed9-4373-8314-1a6b814d348f">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS, and IpadOS
 - Browser [e.g. chrome, safari]: safari
 - Version [e.g. 22]: 17.4.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SebiWrn** [comment]
Fixed the VOD
