### ISSUE TITLE
Add option for DD.MM.YYYY date format

### ISSUE THREAD

**Issue by kaantureyyen** [joschahenningsen/TUM-Live#1360]
**Is your feature request related to a problem? Please describe.**
My European eyes get frustrated when I see the American MM/DD/YYYY date format all over TUM-Live.

**Describe the solution you'd like**
An option in settings to convert the date to the DD.MM.YYYY format. IMO the point separator is optional, but the option for DD MM YYYY is not.

**Describe alternatives you've considered**
Accept defeat to the imperial system :(

**Comment by joschahenningsen** [comment]
Where do you see the American date format? This should be handled by the browser and depends on your system language (at least on the homepage) 

![Screenshot_20240612-085140.png](https://github.com/TUM-Dev/gocast/assets/44805696/ded7dc88-1ff1-4276-834c-010601da6f24)

**Comment by kaantureyyen** [comment]
That is true. But it would still be nice imo to have this as a setting in settings for better personalization.

Many prefer a language list like: English, other languages... Mostly locale settings are also handled over this preference list. But being a German speaker and using European locales overall, I haven't found a way to reproduce a locale selection like e.g. English (Germany).

Would be nice as feature!

**Comment by CommanderStorm** [comment]
<details><summary>Should be possible via toggling this setting in Firefox or am I misunderstanding the FR?</summary>
<p>

![image](https://github.com/TUM-Dev/gocast/assets/26258709/a4f78316-43dd-47fe-98a6-74eb94178bdd)

</p>
</details> 

Hottake: I don't think users want the date format to switch between different tabs
=> leaving this up to the browsers guidance is likely better

**Comment by CommanderStorm** [comment]
(If you want to use Chrome, you can use `English (United Kingdom)` for `dd/mm/yyyy`)

**Comment by kaantureyyen** [comment]
I do see the point in the hot take.
At the end, it's just a preference issue. It don't see the option on Linux Firefox, but just thought it could be a nice enhancement to add this into the settings.
But I feel it is really not that vital at this point, so I'm going to close this as not planned :sun_with_face:
