### ISSUE TITLE
Course material

### ISSUE THREAD

**Issue by josippepic** [joschahenningsen/TUM-Live#1363]
It would be amazing if the lecture slides and the exercises would be available in addition to the lecture itself. (e.g. MIT OpenCourseWare)

**Comment by CommanderStorm** [comment]
FYI: If the lecturer uploads them, they are avaliable.

Here is a screenshot from the lecturer UI:
![image](https://github.com/TUM-Dev/gocast/assets/26258709/f50cea48-3cf0-4654-8b7a-bf97d65b45d4)

From a lecturer point of view, this is quite hidden beind the edit lecture on the top right. In general, I think that the lecturer view is a bit counterintive. (f.ex why are statistics a button next on the settings tab next to "save settings"?)

Also from a lecturers point of view, why would I upload stuff to moodle and tum.live..
