### ISSUE TITLE
All VoDs missing for the course Applications of Mathematical Biology [MA3602]

### ISSUE THREAD

**Issue by jyotishmanh07** [joschahenningsen/TUM-Live#1371]
![image](https://github.com/user-attachments/assets/f6027bd2-4d29-4f1b-9eb3-b26376bcc74f)
the course is missing all the VoDs

**Comment by joschahenningsen** [comment]
The videos available for specific courses and their visibility are managed by the courses respective admins (e.g. Übungsleitung). Please ask them to re-enable access to the videos if you think this change was made on accident. 
Cheers! 🍻
