### ISSUE TITLE
Tum Live Lecture VOD [Mathemathik Vorkurs Informatiks 16.09.24] appears to be damaged and can't be watched with good quality

### ISSUE THREAD

**Issue by Marya-bitte** [joschahenningsen/TUM-Live#1379]
The TUMLive VOD of the Lecture on 16.09.24 for the Mathematik Vorkurs for Informatik can be watched but it the footage appears to be "corrupted" (for lack of a better word) and has extremely poor quality. Also..the original lecture was around 2hrs long and the VOD appears to be 13hrs+ long now.

1. Go to https://live.rbg.tum.de/w/vmi24/47612
2. Click on start video [Play Button]
3. Watch aprox 1 min of footage to get first impression.4. 
4. Click on random intervals of the timeline to assess that the footage is "corrupted" throughout the whole VOD
5. See timeline of the video (look for the length of the lecture, must be around 13:49:46 hours long)

Expected behavior:
I wanted and expected to be able to watch the repetition of a lecture.

Screenshots
![Screen Shot 2024-09-19 at 18 24 11](https://github.com/user-attachments/assets/6d1b35f0-8657-4003-80a1-0b4e1a57b3ea)

Desktop (please complete the following information):
 - OS: [MacOS]
 - Browser [Safari or Opera (tried it on both)]

Additional context:
I was told I could report it here. If not I'd appreciate to be informed where I can report the bug. (Also I know nothing about coding and I'm new to GitHub)

**Comment by kordianbruck** [comment]
We tried to re-convert and repair the original. However it might be that the original is already corrupted. We'll keep you updated.

**Comment by SebiWrn** [comment]
I'm sorry but we tried everything to fix the video but it already got corrupted during the streaming, so we can't fix it.
