### ISSUE TITLE
Cannot see livestreams of courses I am registered to

### ISSUE THREAD

**Issue by danielpetri1** [joschahenningsen/TUM-Live#1385]
**Describe the bug**
I've registered to a lecture on TUM Online under "Freie Anmeldung" and was assigned a "Fixplatz". Even though it's been many days, the lecture does not show up under "My courses".

**Additional context**
Please add a button to "forcefully" re-sync TUM Online with TUM Live.

**Comment by SebiWrn** [comment]
Could you please provide us with your username so we can investigate this problem further?

**Comment by danielpetri1** [comment]
@SebiWrn sure, it's daniel.petri@tum.de (`ga53xus`). I'll delete this for privacy purposes soon

**Comment by danielpetri1** [comment]
@SebiWrn sure! I've sent you an email to the address listed on your profile.
