### ISSUE TITLE
Link to wiki is broken

### ISSUE THREAD

**Issue by nilsreichardt** [joschahenningsen/TUM-Live#1421]
**Describe the bug**
If you click on the Wiki button, you will get a 404 error.

**To Reproduce**
1. Go to https://tum.live/
2. Scroll down to the footer
3. Click on "Wiki"

**Expected behavior**
A working link should open.

**Screenshots**
https://github.com/user-attachments/assets/89b2416f-8fdc-4d3b-88cb-a8aeec2a1ea4

**Additional context**
Related to
* #1355

**Comment by laxerhd** [comment]
I'm not sure, but I think this was just a temporary problem.
Navigating to the `Wiki` from the footer seems to work as usual now.
I think you can close the issue.

**Comment by nilsreichardt** [comment]
Yes, works again - thanks!
