### ISSUE TITLE
The login process is broken

### ISSUE THREAD

**Issue by ShenhanQian** [joschahenningsen/TUM-Live#1423]
**Describe the bug**
The login process is broken

**To Reproduce**
1. Go to ['TUM-live'](https://live.rbg.tum.de/)
2. Click on 'Login'
3. Click on 'TUM Login'
4. Redirected to 'Web Login Service'
5. See error

**Expected behavior**
Successful login

**Screenshots**
![image](https://github.com/user-attachments/assets/226064d4-4500-4d9e-9649-1d4de7a6e112)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Microsoft Edge, Firefox, Chrome

**Comment by CommanderStorm** [comment]
We are aware of this issue of the expired cert and are currently in the process of working with our partners to re-enable the shibotlet login.

In the meantime, please use the internal login function. @AndreasPaul as pushed the following warning-bobel

![If you face issues logging in, please use the internal login function with your TUM credentials for now.](https://github.com/user-attachments/assets/53fca274-e6c7-4935-9d46-bb533f2d675d)

**Comment by ShenhanQian** [comment]
thanks for the prompt reply. The internal login function works for me.

**Comment by joschahenningsen** [comment]
Thanks for reporting, the issue has been resolved 👍
