### ISSUE TITLE
Player UI partially unavailable in fullscreen on iPad Pro

### ISSUE THREAD

**Issue by YourMJK** [joschahenningsen/TUM-Live#148]
**Describe the bug**
Going into fullscreen mode with the web player on an iPad Pro (with rounded corners) will render the buttons in the lower left and right corners (skip 10s back, leave fullscreen) unusable.
Also, using the progress slider in the center to skip in a VOD isn't always possible on the iPad Pro since it's partially obscured by iPadOS's "homebar".

**To Reproduce**
1. Open website with Safari on an iPad Pro (2018+)
2. Open VOD
3. Go into fullscreen mode
4. Try using the _skip back_ button, _leave fullscreen_ button or the progress slider.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/37852512/140079001-5b05ada8-7f35-4f47-90be-a1a4c774a048.png)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11" (2018)
 - OS: iPadOS 14.4.1
 - Browser: Safari

**Comment by joschahenningsen** [comment]
Yikes, thanks for letting me know!

**Comment by CommanderStorm** [comment]
This is weird:
On my iPad Pro (12.9-inch) (3rd gen, released in Late 2018) everything works fine.
I don't see how the admittedly a bit larger display could fix the issues you described. For example the scrollbar works for me and that should not be size-specific.

![20211124_103036.jpg](https://user-images.githubusercontent.com/26258709/143212294-762d22aa-d17d-4cb6-a1ae-79f5b2beb65b.jpg)
(Sorry for the bad picture quality)

The buttons are a bit small on mobile in general though..
Maybe this is the issue?

**Comment by joschahenningsen** [comment]
For me (IPad Pro 5. gen, 12.9") the UI is visible as well, just not clickable. I'm considering a different player, until then I'll add a margin for iPads and maybe resize the UI later today.

**Comment by joschahenningsen** [comment]
Seems fixed
