### ISSUE TITLE
Cannot play VoD on Firefox

### ISSUE THREAD

**Issue by PSandro** [joschahenningsen/TUM-Live#149]
**Describe the bug**
I cannot start playing *some* videos on demand using Mozilla Firefox 93.0 on Ubuntu 21.04. After clicking "play", the following output appears in the console:
![tum_live_bug](https://user-images.githubusercontent.com/20563761/140547403-d82a1fbb-da23-403d-a055-c9c0b2b22347.png)

**To Reproduce**
1. Go to live.rgb.tum.de using Firefox
2. select a VoD (in my Case the ERA Zentralübung (ID 6278 or 6308), some other VoD work just fine
3. error will show in console, stream will not load (loading circle will spin for ever)

**Expected behavior**
The VoD should start playing, just like it does when using chromium.

**Desktop (please complete the following information):**
 - OS: GNU/Linux Ubuntu 21.04
 - Browser firefox
 - Version Mozilla Firefox 93.0

Thanks for looking into it! :smiley:

**Comment by joschahenningsen** [comment]
Thanks for reporting this @PSandro! 
I noticed this as well, I probably need to tweak my encoding params a little more to cope with uncertain inputs (e.g. whatever zoom decides to throw at us)
I opened another issue at https://github.com/joschahenningsen/TUM-Live-Worker-v2/issues/3 to track any technical finds on this. 

Also I'll fix the two era videos tmr :+1:
