### ISSUE TITLE
Video Slow Buffering - Would it be possible to allow watching videos at a lower resolution? 

### ISSUE THREAD

**Issue by anonymousDog12** [joschahenningsen/TUM-Live#150]
It may or may not entirely because of my internet, but the lecture videos buffers or becomes frozen a lot. But I have no problem viewing other videos such as youtube videos or have video calls from another continent. Would it be possible to improve on that? Maybe there can be an option for decreasing resolution?

**Comment by anonymousDog12** [comment]
Ok... I realized it might just be my browser's problem.

**Comment by joschahenningsen** [comment]
I'd still like to know where such issues might come from, did you experience this with live videos or recordings? Which browser did you use? Can you post the results of https://speedtest.in.tum.de? (Preferably at a time you usually experienced this)

Thanks for helping out :)

**Comment by anonymousDog12** [comment]
Not live videos. Just the recordings. I was using Chrome and it was very slow, but when I switched to Safari everything works smoothly. I think it's just Chrome; it has been slow for a while now. And I can't seem to open the speed test link.
