### ISSUE TITLE
VOD options not shown

### ISSUE THREAD

**Issue by fh314** [joschahenningsen/TUM-Live#151]
**Describe the bug**
The options to edit or set a VOD recording private are not shown as documented in the wiki here https://github.com/joschahenningsen/TUM-Live/wiki/Using-TUM-Live-as-a-lecturer#after-the-stream

**To Reproduce**
1. Go to the Admin tab of a past lecture and expand one of the recorded past lectures
4. You'll only see two buttons to download the vod recording and to access the statistics

**Expected behavior**
See additional buttons to edit start and end or to set recording private

**Screenshots**
![image](https://user-images.githubusercontent.com/29736922/140971183-096edd52-69b5-4618-8055-3b1054528b40.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64Bit
 - Browser: Chrome 95.0.4638.69 and Edge 95.0.1020.44

**Comment by joschahenningsen** [comment]
Seems like the UI is a little broken in general, looking into it. Do you need something hidden urgently?

**Comment by fh314** [comment]
No, nothing too urgent

**Comment by danieljvaz** [comment]
I would also find this useful, as I prefer doing some local video editing and re-uploading (but keeping the original files is useful as backup).
