### ISSUE TITLE
Viewer statistics of livestream not shown when VoD is disabled

### ISSUE THREAD

**Issue by fh314** [joschahenningsen/TUM-Live#152]
**Describe the bug**
When disabling VoD in a course, the viewer statistics graph can't be viewed after a lecture has ended

**To Reproduce**
1. Hold a live stream while VoD is disabled for the course
2. Try to access the viewer statistics graph after finishing the Livestream
4. See that graph is missing

Actual:
![image](https://user-images.githubusercontent.com/29736922/142038220-04e98c41-7113-4c5d-8df4-75201736e20c.png)

**Expected behavior**
Expected (also when VoD is disabled):
![image](https://user-images.githubusercontent.com/29736922/142038136-99fdfefb-4744-4e07-80e2-ad83f91e1094.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64Bit
 - Browser: Chrome
 - Version: 96.0.4664.45

**Comment by joschahenningsen** [comment]
Closing this for staleness and because the UI is entirely different now.
