### ISSUE TITLE
End streams early

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#171]
**Is your feature request related to a problem? Please describe.**
Often, lecturers either end their lectures early or don't show up. The streams continues nonetheless, this eats resources (computing power and disk space) 

**Describe the solution you'd like**
Every live stream needs a button for admins and lecturers that allows them to end the stream. This should include a prompt whether or not to discard the recording as well (in case no one was there we don't need to create a vod.)

**Comment by alexanderstephan** [comment]
I'd love to work on this. I am really interested in getting some more experience with gRPC and finally getting to know the worker a bit better (without breaking anything hopefully :sweat_smile: ).
