### ISSUE TITLE
Refactor index.go data operations into dao

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#191]
**Is your feature request related to a problem? Please describe.**
Loading the courses in [index.go](https://github.com/joschahenningsen/TUM-Live/blob/dev/web/index.go) could be faster.

**Describe the solution you'd like**
Prepare the data in the dao accordingly to avoid sorting and filtering in `index.go`.

**Comment by joschahenningsen** [comment]
That would be cool, this function is way too heavy, even breaking it down into a few manageable functions would be cool :+1:
