### ISSUE TITLE
[Stream management]: Bulk change lecture hall

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#224]

**Comment by mono424** [comment]
@joschahenningsen what exactly should be bulk changeable? is there some kind of a list of actions? :)

**Comment by joschahenningsen** [comment]
The stream model has an attribute called `lecture_hall_id`, this can already be changed through the UI here: 
![image](https://user-images.githubusercontent.com/44805696/149626261-de048df3-53c2-4571-ac89-6ad23aed3f6a.png)

It would be cool to do this as a bulk action as well :)
