### ISSUE TITLE
Several CSS errors and warnings

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#225]
**Describe the bug**
Every site that includes `main.css` causes several warnings.

**To Reproduce**
Go to _live.rbg.tum.de_ and view the inspector.

**Expected behavior**
No warnings regarding CSS on any page.

**Screenshots**
This is what it mostly looks like:
![image](https://user-images.githubusercontent.com/30267166/148832820-0329a879-c0c7-4702-9885-1812b32640d4.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser Firefox
 - Version 96.0

**Comment by joschahenningsen** [comment]
Some of the scrollbar stuff seems to be acting up. This is a little annoying because all browsers handle this differently. 

Are you sure you're using FF 23 though? Thought latest would be around 95

**Comment by alexanderstephan** [comment]
Yes, you're right. I use Firefox 96.0, I just updated it. :+1:

**Comment by alexanderstephan** [comment]
This seems impossible to solve as browsers are just too different at the moment...
