### ISSUE TITLE
Presentation only/camera only streams

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#226]
**Is your feature request related to a problem? Please describe.**
Some profs only use the blackboard or don't need a camera image, they only need one of the three streams. 

**Describe the solution you'd like**
On the stream administration page, select **camera only** or **presentation only**. The selected stream should be streamed as default (`playlist_url`)

**Comment by ata-keskin** [comment]
I would like to work on this. I will add a pull request once I make progress.

**Comment by joschahenningsen** [comment]
Nice! Hmu if you need any assistance, happy to talk on Discord :)
