### ISSUE TITLE
Fix "back button" for statistics

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#235]
**Describe the bug**
There is a "back" button in the Admin statistics tab, that only works if one clicks "View more Stats" in the admin course overview. Otherwise it will just delete the current address in the address bar.

**To Reproduce**
1. Go to Admin Tabs
2. Click on Statistics
3. Click on the "back" button shown above

**Expected behavior**
The back button is hidden when it does nothing.

**Screenshots**
![image](https://user-images.githubusercontent.com/30267166/149767435-60121fdd-e55f-4279-946e-f3097443a896.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser: Firefox
 - Version: 96

**Comment by joschahenningsen** [comment]
IMO this button should be removed, browsers have :sparkles: inbuild navigation :sparkles:  :D
