### ISSUE TITLE
Stream ingest URL is not visible until reload after changing stream to selfstream

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#236]

**Comment by ata-keskin** [comment]
I would like to work on this issue. I will add a pull request once I make progress.

**Comment by ata-keskin** [comment]
Hi, I'd like to proceed with this issue but I wasn't able find the files related to this issue. Could you point me in the right direction? I hope I can understand the issue better by looking at the relevant source files :)
@joschahenningsen

**Comment by joschahenningsen** [comment]
I'm afraid, this issue was already fixed in #389 (by accident even :smile: )

**Comment by joschahenningsen** [comment]
Now that the issue is fixed, you can directly copy the streaming keys when switching to selfstream:

https://user-images.githubusercontent.com/44805696/167418423-0844625c-57ab-4fcf-b8de-080ac76da7c2.mp4
