### ISSUE TITLE
Only months change order

### ISSUE THREAD

**Issue by christophhehl** [joschahenningsen/TUM-Live#240]
If you change the order of the lectures, it only changes the order of the months but not of the lectures within.
No matter if the months are ascending or descending, the newest lecture of a month is always on top.

Expected behavior:
The lectures within a month should also change order.
![Ascending Order](https://user-images.githubusercontent.com/44849271/150343843-d460dc83-041a-48df-aefa-1cbd795d14b3.png)
![Descending Order](https://user-images.githubusercontent.com/44849271/150343849-a1ab9589-e01c-4474-a938-1d45655ffd8b.png)

**Comment by MatthiasReumann** [comment]
This was meant to be a feature, but now if I think about it, it doesn't really makes sense 😅 Will be fixed!
