### ISSUE TITLE
Chat scrolls automatically when in the not at the bottom

### ISSUE THREAD

**Issue by mariusdkm** [joschahenningsen/TUM-Live#241]
**Describe the bug**
When the chat isn't scrolled to the most bottom message and a new message appears, the chat jumps to the bottom.

**To Reproduce**
View any live chat.
Scroll to the middle.
Write a chat message with another window.
Result: The chat scrolls to the bottom to the new message

**Expected behavior**
When scrolled to a message, the chat should stay at that message and should not scroll down when a new one appears.
That makes it really hard to read past chat messages, because one always has to scroll up again.

**Desktop:**
 - OS: MacOS
 - Browser: Firefox
 - Version: 96.0.2

**Comment by mariusdkm** [comment]
Just saw #40

**Comment by joschahenningsen** [comment]
reopening this and closing #40 to bump this :) thanks!
