### ISSUE TITLE
Pop out chat

### ISSUE THREAD

**Issue by LukaTomas** [joschahenningsen/TUM-Live#296]
It bothers me that there is no option to watch the stream in fullscreen mode and have a look at the chat at the same time. Adding something like a pop out button for the chat, where the chat would be displayed in a seperate new window would be nice. This way, one could whatch the stream in fullscreen and have the chat on a second screen.

**Comment by joschahenningsen** [comment]
:+1: This is a must-have. Linked issue: #292

**Comment by alexanderstephan** [comment]
Thanks for creating the issue! :+1:

**Comment by alexanderstephan** [comment]
@LukaTomas The feature is now live btw :grinning:
@joschahenningsen I think we can close this and https://github.com/joschahenningsen/TUM-Live/issues/292, right?
