### ISSUE TITLE
404 Error Page

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#322]
**Is your feature request related to a problem? Please describe.**
When visiting a link nothing really happens right now. This can be a bit misleading.

**Describe the solution you'd like**
Show a nice (maybe even funny) 404 page.

**Comment by joschahenningsen** [comment]
How about using these? https://http.cat/ 
Unsure about the copyright implications of using https://giphy.com/explore/confused-travolta
