### ISSUE TITLE
How-To Pages 

### ISSUE THREAD

**Issue by MatthiasReumann** [joschahenningsen/TUM-Live#329]
**Describe the solution you'd like**
Extend the GitHub-Wiki and the docs (https://docs.live.mm.rbg.tum.de/) with How-To pages that describe how certain features work. For the time being the chat features would suffice.

**Comment by joschahenningsen** [comment]
I started using the wiki for this a while back, I'd be fine with extending it https://github.com/joschahenningsen/TUM-Live/wiki
Alternatively there could be how-to-guides in the docs: https://docs.live.mm.rbg.tum.de/
