### ISSUE TITLE
.ics file for course

### ISSUE THREAD

**Issue by MatthiasReumann** [joschahenningsen/TUM-Live#330]
**Describe the solution you'd like**
It would be really nice if it were possible to download a .ics file for a course in a semester.

**Comment by ata-keskin** [comment]
I would be interested in implementing a tool for this purpose that could be available on the TUM-Live website. For example on the main page of courses.

**Comment by MatthiasReumann** [comment]
Hey great! You might want to have a look at these links: 
- https://www.npmjs.com/package/ics (Package for creating ics content)
- https://aweirdimagination.net/2015/03/02/generate-and-download-file-in-typescript/ (Create files locally)

The dates of all streams are stored in the `TUMLiveContext`. For example, in `course.gohtml` you can get them
in the template with `{{$course.Streams}}` which is an array of the model `Stream`. With the help of [Alpine](https://alpinejs.dev) you can even store them conveniently with `<div x-data="{'streams': {{$course.Streams}}}"...`

**Comment by joschahenningsen** [comment]
We actually already create an ics file for all streams that can be consumed by our lecture hall hardware: https://live.rbg.tum.de/api/hall/all.ics

See also: https://github.com/joschahenningsen/TUM-Live/blob/dev/api/template/ical.gotemplate and https://github.com/joschahenningsen/TUM-Live/blob/dev/api/lecture_halls.go#L279

We might use a similar approach, but this is up to you :)

**Comment by CommanderStorm** [comment]
> It would be really nice if it were possible to download a .ics file for a course in a semester.

Note that TUMOnline already exports these ics files (even though a little hidden).
There also is this converter https://cal.bruck.me/ for cleaning the content.

This does however not include the extra titles some lecturers put the extra effort in, to write down.
