### ISSUE TITLE
Video sections

### ISSUE THREAD

**Issue by MatthiasReumann** [joschahenningsen/TUM-Live#339]
**Is your feature request related to a problem? Please describe.**
Course Admins should be allowed to add timestamps with section names for each lecture.

**Describe the solution you'd like**
Simple UI on the admin dashboard to add timestamps and section names. The sections will then be displayed beneath the VOD. A click on a section will jump to the timestamp in the VOD. For example, YouTube's solution looks like the following: 

<img width="762" alt="image" src="https://user-images.githubusercontent.com/29633518/161042113-86f6b20b-59db-46f9-b7a2-f0ee5998ace1.png">

**Comment by joschahenningsen** [comment]
Sounds sick 🔥 
We'll just have to hope that lecturers actually use it 😀

**Comment by MatthiasReumann** [comment]
We could think about implementing subtle 'notifications' on the admin pages which informs them about new features. A bit of a change-log maybe?. 🤔

**Comment by joschahenningsen** [comment]
Yup, Alex and I thought about something like the notification bell on
GitHub. This could show feature alerts based on what role the logged in
user has.
