### ISSUE TITLE
Loadtest issues

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#34]
This is where you can leave comments on problems that occured during the load testing of TUM-Live on 31. March 2021. If it feels relevant please open a new issue.
You can also use reactions below to vote on problems.

reaction | :-1: | :laughing: | :confused: | :rocket: | :eyes: 
--- | --- | --- | --- | --- | ---
issue | Page load slow | issue displaying site | much buffering  | problems logging in | chat doesn't work

If possible provide details from the developer console (such as http status codes or console messages)

**Comment by ga62suz** [comment]
comments / chat on the stream needed a while to show up after they're entered (~14 secs).

Edit: This seems to be not the issue but rather the chat page is extended beyond viewable area at the bottom, meaning new messages are not seen unless a newer message pushes them upwards. (Firefox on Windows 10)

**Comment by Trattue** [comment]
Sometimes number of viewers isn't displayed
Edit: Also scrolling in chat seems to be broken sometimes, even scrolling down manually won't work
Edit 2: Resizing the window moves the chat up
Edit 3: ~~Sending empty messages is possible~~ fixed
Edit 4: I'm using Firefox 87.0 on a Windows 10 machine

**Comment by Jolly5** [comment]
> Edit: Also scrolling seems to be broken sometimes, even scrolling down manually won't work

Exactly, I cannot scroll further at this point.
Element inspector reveals there's one more line to that last message.

![Screenshot](https://user-images.githubusercontent.com/28727778/113175370-a5651600-924b-11eb-8e6b-8e22ec576752.jpg)

The problem repeatedly solves itself when new messages appear and reappears later.

~~Edit: It seems like the problem appears if a message is received while your chat is not completely scrolled to the bottom.~~
Edit 2: No, also happens without that :D
Edit 3: So yeah, this is all just because the "Send a message" form overlaps the chat. If the most recent message is only a single line, it is obscured completely, making it seem like everything was fine.

**Comment by Raupinger** [comment]
I also experience the cutoff issue. Using Firefox 86.0 (build nr 20210228220141). Refreshing doesn't solve it.

**Comment by joschahenningsen** [comment]
@Raupinger, I'll test on your version of Firefox soon! Which OS do you use?

**Comment by ZofiaZementa** [comment]
I have the same issue on Mozilla Firefox 87.0  BuildNr 20210324205532
I'm using Fedora 33 5.11.7-200.fc33.x86_64

**Comment by Jojaa350** [comment]
> 
> 
> I also experience the cutoff issue. Using Firefox 86.0 (build nr 20210228220141). Refreshing doesn't solve it.

Same for Firefox 87.0, Windows 10; Changing `max-height: calc(100vh - 5rem);` to `max-height: calc(100vh - 9rem);` in main.css line 1390 (in `.chat`-class for `@media(min-width: 768px)`) fixes that, but might not be the optimal solution for other browsers.

**Comment by Raupinger** [comment]
Posting [this](https://pastebin.com/BxkwMYp9) Message with a large amount of unicode modifiers completely hangs up the chat. Don't see any new messages and cant send anything. reloading solves the problem.

**Comment by Raupinger** [comment]
> @Raupinger, I'll test on your version of Firefox soon! Which OS do you use?

that would be Manjaro Linux. 
```
$ uname -a
Linux florian-pc 5.10.19-1-MANJARO #1 SMP PREEMPT Fri Feb 26 11:38:34 UTC 2021 x86_64 GNU/Linux
```

**Comment by RobinMarchart** [comment]
Also rendering all messages might lead to unnecessary high memory consumption ond/or slow scrolling

**Comment by Jolly5** [comment]
You requested the error messages from the console - those are mine:

![Screenshot](https://user-images.githubusercontent.com/28727778/113179102-941e0880-924f-11eb-88a4-cfbfec186b6a.jpg)

Firefox 64-Bit 87.0
Windows 10 20H2 (Build 19042.867)

Edit 1: Those were the shown messages after a single page refresh and pressing the play button on the video.

**Comment by Trattue** [comment]
~~Maybe some kind of chat cooldown should be implemented ^^~~ done

**Comment by Raupinger** [comment]
and i got an error
![grafik](https://user-images.githubusercontent.com/29229062/113179813-4c4bb100-9250-11eb-9ad4-26ff2d1212ce.png)
text is [here](https://pastebin.com/YzEkD7dh)

**Comment by Hofmer13** [comment]
I'm using Firefox 87.0, Linux.

- Bottom of the chat is cut off (as reported above already).
- Participator count wasn't displayed. Refreshing helped, can't reproduce reliably.
- Some chat messages seem to get lost.
- The course name ("Lasttest") is displayed at the very bottom, are we supposed to be able to scroll? Edit: If you make your window very flat, you can't even see the whole video.
- Stream seems to be stuck at loading. (The loading circle thing keeps being there and the stream doesn't play reliably.)
- The bad at the bottom of the video is sometimes invisible. I still get the tooltip info (like "Mute"), but the symbols are not displayed.

<details> <summary> console output </summary>

![2021-03-31-184215_1920x1080_scrot](https://user-images.githubusercontent.com/59291908/113180468-0f33ee80-9251-11eb-9330-3b0c3097783a.png)


```
Fehler beim Verarbeiten des Wertes für '-webkit-text-size-adjust'.  Deklaration ignoriert. main.css:37:29
Unbekannte Pseudoklasse oder Pseudoelement '-ms-input-placeholder'.  Regelsatz wegen ungültigem Selektor ignoriert. main.css:416:7
Regelsatz wegen ungültigem Selektor ignoriert. main.css:536:8
Das angegebene "type"-Attribut "application/x-mpegURL" wird nicht unterstützt. Das Laden der Medienressource https://live.stream.lrz.de/livetum/test/playlist.m3u8 ist fehlgeschlagen. 26
Alle Kandidaten für die Ressource konnten nicht geladen werden. Medien-Laden pausiert. 26
Uncaught ReferenceError: Get is not defined
    loadStat watch.ts:34
    Watch watch.ts:16
    <anonymous> watch.ts:72
watch.ts:34:19
VIDEOJS: WARN: A plugin named "reloadSourceOnError" already exists. You may want to avoid re-registering plugins! video.min.js:12:750
Alle Kandidaten für die Ressource konnten nicht geladen werden. Medien-Laden pausiert. 26
MouseEvent.mozPressure sollte nicht mehr verwendet werden. Verwenden Sie PointerEvent.pressure stattdessen. video.min.js:12:9084
XHRGEThttps://videostream02.srv.lrz.de/livetum/_definst_/test/media_w258276566_1605.ts
```

</details>

Edit: I'm also getting lots of these error messages:

<details>

![2021-03-31-184840_1920x1080_scrot](https://user-images.githubusercontent.com/59291908/113181397-ff68da00-9251-11eb-82db-fe5e839d0a6d.png)


```
VIDEOJS: ERROR: DOMException: An attempt was made to use an object that is not, or is no longer, usable video.min.js:12:750
    e https://live.mm.rbg.tum.de/dist/video.js/dist/video.min.js:12
    error https://live.mm.rbg.tum.de/dist/video.js/dist/video.min.js:12
    dispatcher https://live.mm.rbg.tum.de/dist/video.js/dist/video.min.js:12
    pe https://live.mm.rbg.tum.de/dist/video.js/dist/video.min.js:12
    trigger https://live.mm.rbg.tum.de/dist/video.js/dist/video.min.js:12
    value https://live.mm.rbg.tum.de/dist/@videojs/http-streaming/dist/videojs-http-streaming.min.js:9
    request https://live.mm.rbg.tum.de/dist/@videojs/http-streaming/dist/videojs-http-streaming.min.js:9
    s https://live.mm.rbg.tum.de/dist/@videojs/http-streaming/dist/videojs-http-streaming.min.js:9
    s https://live.mm.rbg.tum.de/dist/video.js/dist/video.min.js:19
    e https://live.mm.rbg.tum.de/dist/video.js/dist/video.min.js:19
```

</details>

**Comment by joschahenningsen** [comment]
Cut off chat will be fixed sometime before the semester starts.

**Comment by joschahenningsen** [comment]
@ all Thank's a lot, you've been incredibly helpful!
![image](https://user-images.githubusercontent.com/44805696/113188223-0dbaf400-925a-11eb-8130-b5b791907b40.png)
