### ISSUE TITLE
Owner can also be admin and sees course twice

### ISSUE THREAD

**Issue by dfherr** [joschahenningsen/TUM-Live#354]
I created a new course (id 283) and then noticed there were no admins, so I added myself as admin. Now I see the the course twice on the admin management panel to the right.

![image](https://user-images.githubusercontent.com/6793674/161727529-922bfbbe-e02f-4859-af8d-ec653ce73d54.png)

Removing myself from the admins again still lets me have admin privileges (I assume because I'm the creator/owner):

![image](https://user-images.githubusercontent.com/6793674/161727723-6d965985-3060-427c-8fd3-dbffb17035a2.png)

**Expected behavior**

The owner of a course should be a super-role of the admin and displayed as "owner" or regular "admin" in the list of "Course Admins" in the admin panel.

**Comment by dfherr** [comment]
To add to that, now that I removed myself from the admins again, the remove button of my co-admin (which I also added) is greyed out. So I can manage the course, I can add more admins, but I can't remove the currently only visible admin.

![image](https://user-images.githubusercontent.com/6793674/161730393-1a388a50-35a2-4dad-a5a1-033d89b59929.png)

I asumme this behavior is meant for rbg employees creating courses not showing up there, but it's really confusing when a lecturer creates his own course :)

**Comment by joschahenningsen** [comment]
Thanks for the report, you are absolutely right, this is very confusing. As a quick fix, the list should at least not contain duplicates.
