### ISSUE TITLE
Separate link/s for data privacy statement and imprint

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#359]
The data privacy statement and imprint should both be directly accessible from the start page or ideally from all pages. Either in a sticky footer or the header (the design should be rather discreet).
Additionally, those pages should not be Hardcoded but rather provided as a markdown file that is then rendered in HTML (like video descriptions for example)

**Comment by alexanderstephan** [comment]
I guess this can be closed now since https://github.com/joschahenningsen/TUM-Live/pull/489 is merged?
