### ISSUE TITLE
Create course: year and semester should not be text Inputs 

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#361]
When creating a course, the semester selection must be typed in in a specific format, this is very inaccessible.
The inputs should be checkboxes, option inputs, dropdowns or similar.

**Comment by Mohrimn** [comment]
Hey, not sure if you are actively looking for help but if you do I would l like to contribute to your project and work on this issue.

**Comment by joschahenningsen** [comment]
Hi @Mohrimn Help is always appreciated! Feel free to have a look [here](https://github.com/joschahenningsen/TUM-Live/discussions/336#discussioncomment-2585559) if you need any advice on setting up the project (and of course always ping me if there are any questions) :)

**Comment by Mohrimn** [comment]
Hi @joschahenningsen I have a question about the setup instructions in the readme file about getting go running locally, it mentions that I should add the environment variables from 'variables-backend.example.env'. I cannot find this file, am I missing something?

**Comment by joschahenningsen** [comment]
> Hi @joschahenningsen I have a question about the setup instructions in the readme file about getting go running locally, it mentions that I should add the environment variables from 'variables-backend.example.env'. I cannot find this file, am I missing something?

Ah thanks for the hint! We don't use environment variables anymore, that point can be removed from the readme. We switched to a proper config file some time ago :)
