### ISSUE TITLE
Add Hot-Reload support

### ISSUE THREAD

**Issue by mono424** [joschahenningsen/TUM-Live#366]
TUM-Live Server should serve the current GOHTML pages when they are changed. 
Currently a server restart is needed.

**Comment by joschahenningsen** [comment]
Some context: currently the application embeds the `.gohtml` files into the binary, so restarting tum Live is required whenever something changed. When developing tum Live, these templates should be read from disk (there's a handy variable, `VersionTag` that indicates whether we're on a dev maschine or on prod). 
The templates are also parsed using `template.Must(...)` which crashes tum Live at startup time if there are errors in the template, maybe this should be changed for dev envs as well. 

Additionally, tailwind assets are currently not included in the `build dev` configuration, this would be cool as well.
