### ISSUE TITLE
Upcoming lectures are sorted in the wrong way

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#370]
The lectures should be sorted such that the next lectures are on top of the page:

![image](https://user-images.githubusercontent.com/44805696/163972305-d3477853-155e-4775-aa63-c1785b6da9f4.png)

**Comment by jpbernius** [comment]
I think this is broken again.
https://live.rbg.tum.de/course/2022/W/pse

From how I understand the history, the changes from #372 were overwritten in #486.
