### ISSUE TITLE
Pin courses to the top

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#373]
Courses could be pinnable to the top of the start page. This could be used for interesting courses that one is not registered for and that are publicly available. This could be also across different semesters e.g. when using an old recording. It could land in another section like "My courses". Courses could have a small menu for actions with a pin needle.

**Comment by barisconur** [comment]
I want to work on this issue

**Comment by ata-keskin** [comment]
Is this being worked on currently? If not I can take it over.

**Comment by alexanderstephan** [comment]
Nope, would be cool if you could this over. :+1:

**Comment by ata-keskin** [comment]
Alright. I am on it!
