### ISSUE TITLE
Show admin user-search results in same table

### ISSUE THREAD

**Issue by MatthiasReumann** [joschahenningsen/TUM-Live#379]
**Is your feature request related to a problem? Please describe.**
Currently, if an admin searches for users a new table, which looks completely different UI wise, is displayed. Results should be shown in the "normal" table.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/29633518/164042645-637c0042-a2c9-42f3-9458-ba5c899faf47.png">

Alternatively, the user search could be moved somewhere else. (Or something like a modal dialog)

**Comment by joschahenningsen** [comment]
Yeah, that would be great! 
The issue there was, that the users are initially preloaded as html using `gohtml` syntax but the user search is a api based search using alpine. IMO we could just change it all to alpine and load the initial users using some api.

**Comment by alexanderstephan** [comment]
Maybe we could do something similar to the watched states in the course page, where the client gets a JSON string via the go template context. This is flexible and avoids the initial API call that would fetch the whole user list.
