### ISSUE TITLE
Improve semester selection user experience

### ISSUE THREAD

**Issue by Trattue** [joschahenningsen/TUM-Live#38]
It is possible to access semesters that do not have any courses [1] and the semester selection does display those. While this doesn't cause any issues, displaying semesters without any content (not even restricted content) might confuse users. Maybe those could be filtered out?

Also, imho the current semester selection [2] does not make it clear there are other semesters than the ones currently displayed in the semester selection. Maybe some kind of visual indicator can be used to reflect this more clearly?

Apart from that I really love the new site, thanks for working on this ^^

[1] as an extreme example, one can access [/semester/-4201337/W](https://live.mm.rbg.tum.de/semester/-4201337/W)
[2] ![grafik](https://user-images.githubusercontent.com/63713970/112822392-2b386400-9088-11eb-9ca0-39f829b39226.png)

**Comment by joschahenningsen** [comment]
Noticed a few folks experimenting how far they could go :smile: 
I'm not concerned about any issues this might cause but from a UX perspective it might be nice to limit the links shown :+1: 

> Apart from that I really love the new site, thanks for working on this ^^

Thanks!

**Comment by joschahenningsen** [comment]
Changes will land soon, might need some more fiddling when there are more than a handful of semesters though.
