### ISSUE TITLE
Fix statistics

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#380]
Statistics went a bit crazy again. I am not sure what the issue is though. Looks like it happened just when the lecture period ended, so it might be something related to that.
The values seem to be correct, but the x axis position of the values is off.

Reference:
![grafik](https://user-images.githubusercontent.com/30267166/164087590-82e04d48-3359-4411-b028-44b268206a10.png)

**Comment by joschahenningsen** [comment]
This happens in graphs where there are live **and** vod statistics, but some months are missing in either of the datasets that are present in the other. 

To keep the fix simple (and possibly make the stats page more useful as well) we should probably separate the graphs into two.
