### ISSUE TITLE
tools/camera shells out to curl

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#382]
https://github.com/joschahenningsen/TUM-Live/blob/dev/tools/camera/camera.go#L92-L100

There is no need to require `curl`, the `net/http` package should be sufficient to make these requests.

**Comment by MatthiasReumann** [comment]
As it seems Digest Authentication isn't integrated in the `net/http` module yet (See: https://github.com/golang/go/issues/29409)

So the question now is if we should include something like https://github.com/delphinus/go-digest-request, https://github.com/abbot/go-http-auth, or implement an own solution.
