### ISSUE TITLE
Some icons are broken on iPadOS

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#383]
![image](https://user-images.githubusercontent.com/44805696/164531581-f13b0fc7-04e9-42c0-bf63-6bc35445d975.jpeg)

**Comment by joschahenningsen** [comment]
Maybe these are cached from before some fontawesome update? Don't know though.

**Comment by joschahenningsen** [comment]
Yes, seems to be the cache, the Version tag should probably be appended to the font url. I'd still like to **not** serve the whole fa bundle in the future.

**Comment by wasnertobias** [comment]
![DA9EC26E-F241-4A6F-882C-3D52EB8ACDD0](https://user-images.githubusercontent.com/1354793/165251386-77fc73fb-ae37-488a-b83c-a47efabbbfa6.jpeg)

play/pause also seems to be broken at least partly (reproduce with „play“, „skip“, „skip“ on not yet started stream)

**Comment by alexanderstephan** [comment]
I just tried this again. Seems like this is fixed again. :tada:

**Comment by joschahenningsen** [comment]
This was a caching issue after updating fontawesome.
