### ISSUE TITLE
Add keyboard shortcuts for seeking forward/backward in playback of recordings

### ISSUE THREAD

**Issue by A-Sam** [joschahenningsen/TUM-Live#398]
**Is your feature request related to a problem? Please describe.**
I always use the keyboard to navigate through the recordings, but they seem not to work on different platforms

**Describe the solution you'd like**
right and left keys should map to seek forward/backwards as keyboard shortcuts for easier navigation in recordings

**Describe alternatives you've considered**
there is a seek forward/backward dedicated buttons in the playback bar via cursor, but it's not convenient

**Additional context**
None

**Comment by alexanderstephan** [comment]
Related issue: https://github.com/joschahenningsen/TUM-Live/issues/43

**Comment by LadnerJonas** [comment]
Suggestion: use hotkeys of YouTube
https://support.google.com/youtube/answer/7631406?hl=en
Especially: Spacebar (pause/resume), m (mute toggle), f (fullscreen), <>/+- (speed up/ slow down replay speed), j l / left arror, right arrow (skip 5/10 sec back or forward)
