### ISSUE TITLE
Download button for lecture recordings

### ISSUE THREAD

**Issue by avrecum** [joschahenningsen/TUM-Live#401]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am on a long train ride and my internet connection interrupts, which means I cannot watch a lecture recording continuously. Downloading a few videos ahead of traveling solves the problem. There are Chrome extensions that allow stream downloads, but some of them don't work reliably and it's a much bigger hassle compared to just being able to do it directly.

**Describe the solution you'd like**
Download button for lecture recordings.

**Describe alternatives you've considered**
Just do it myself with an extension.

**Additional context**
None

**Comment by joschahenningsen** [comment]
This feature already exists. Logged in users should be able to download this lecture for example: https://live.rbg.tum.de/w/LRZTests/14092 Unfortunately lecturers need to give explicit permission to make their lectures available for download. My only suggestion is to spam your prof until they enable downloads :D 

Sorry for the not too exciting news :/ 

![image](https://user-images.githubusercontent.com/44805696/165938810-7075ccf3-2fb1-48a3-9c40-037243351b6b.png)

**Comment by joschahenningsen** [comment]
Maybe this is still alive? https://github.com/Valentin-Metz/tum_video_scraper

Otherwise it should not be too hard downloading streams using the hls url you can copy below the video and ffmpeg
