### ISSUE TITLE
Multiline message with Shift+Enter

### ISSUE THREAD

**Issue by derkaczda** [joschahenningsen/TUM-Live#41]
**Is your feature request related to a problem? Please describe.**
It is not possible to write multiline messages in the chat without sending the line. 

**Describe the solution you'd like**
Other chat clients use for example Shift+Enter to get a new line without sending the message.

**Comment by Trattue** [comment]
This can be used to create really long messages despite having a message character limit, so probably consecutive line wraps should be ignored

**Comment by joschahenningsen** [comment]
@Trattue Good catch!

**Comment by joschahenningsen** [comment]
Let's track this in #747
