### ISSUE TITLE
Aspect Ratio in combined view in incorrect which reduces presentation size

### ISSUE THREAD

**Issue by A-Sam** [joschahenningsen/TUM-Live#418]
**Describe the bug**
When user chooses combined view (presentation + camera), the view has dead space which reduces the presentation screen size

**To Reproduce**
- Activate combined view from the bottom bar in playback mode

**Expected behavior**
no dead area -> better aspect ratio

**Screenshots**
![screenshot_20220501182701](https://user-images.githubusercontent.com/11005214/166155279-a2801481-4999-4037-a18f-27e50f2aa804.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave
 - Version 1.35

**Additional context**
None

**Comment by A-Sam** [comment]
Related to #342

**Comment by joschahenningsen** [comment]
The aspect ratio is not wrong per se, it's rather just a 16 by 9 video with a black bar at the bottom.

Any idea how two 16/9 videos can be combined into one without this effect? Previous consideration included:
- have the camera overlap the presentation and possibly loose part of it
- deliver another aspect ratio than 16/9 for the comb view (@AndreasPaul is this possible with our hardware?)
- only allow profs to show 4/3 slides so we can show them larger? :smile: 

IMO, a 21/9 Comb video would be sick but it might be much easier to build a nice view with both, camera and presentation streams, that could even be resizable. (see #120)

**Comment by joschahenningsen** [comment]
The predecessor of TUM-Live had the possibility to show both streams side by side, I imagine something similar:

![image](https://user-images.githubusercontent.com/44805696/166162376-ff5a1ce5-7b0a-4527-8f6d-8cef081d8a23.png)

**Comment by A-Sam** [comment]
> * deliver another aspect ratio than 16/9 for the comb view (@AndreasPaul is this possible with our hardware?)
> IMO, a 21/9 Comb video would be sick but it might be much easier to build a nice view with both, camera and presentation streams, that could even be resizable. (see #120)

I'd go for that. Considering the other 2 have more -ve sides on the readability of the presentation.

But I have a question, there is a black/empty space around both views. And when I click anywhere on it it seems to activate play/pause so it's an active area of the playback but is not included in the space of either the Camera nor presentation windows. I'm talking about this:
![screenshot_20220501232732](https://user-images.githubusercontent.com/11005214/166165314-d8507e85-7f57-40c2-a994-c6adf565574d.png)

This question is, can we utilize this space? In this case I can imagine this is a suitable solution while keeping the 16:9 aspect ratio by expanding the presentation to stretch over the playback canvas and move the camera to any of the side black bars:
![screenshot_20220501182701](https://user-images.githubusercontent.com/11005214/166165388-4313a233-fd71-4697-8642-ce1025719062.png)

The only problem may happen if you have a weird looking screen with 4:3 aspect ratio which i don't think they exist :D. this would be a strange looking laptop

**Comment by A-Sam** [comment]
> The predecessor of TUM-Live had the possibility to show both streams side by side, I imagine something similar:
> 
> ![image](https://user-images.githubusercontent.com/44805696/166162376-ff5a1ce5-7b0a-4527-8f6d-8cef081d8a23.png)

This would affect readability because I think the students will want to see the presentation and read it easier. I find my self going to fullscreen mode more often to improve readability

**Comment by A-Sam** [comment]
We could use only 16:9 aspect ratio for camera which i think is the case, and envelope the presentation whatever it is in 16:9 canvas, this will make it easier to align them as i proposed above.
But not sure about the technical difficulty honestly so it's a shot in the dark 😄

**Comment by WafaAmr** [comment]
I would suggest adding an option in the setting to set the Combined view aspect ratio and Presentation:Camera ratio.
For example, 21:9 for The Combined view, and set Presentation:Camera ratio to 1:1.

**Comment by tomresan** [comment]
> I would suggest adding an option in the setting to set the Combined view aspect ratio and Presentation:Camera ratio. For example, 21:9 for The Combined view, and set Presentation:Camera ratio to 1:1.

I also really like the idea of being able to dynamically adjust the ratio between the camera and the presentation. E.g. I am struggling to read the blackboard when in split view, so I always have to change depending on whether the teacher writes something on the blackboard or is talking about the slides.

As a possible inspiration, see [SlidesLive](https://slideslive.com/library) for example.

**Comment by AndreasPaul** [comment]
>     * deliver another aspect ratio than 16/9 for the comb view (@AndreasPaul is this possible with our hardware?)

It's possible but from what I understand the hardware has unresolved issues with storing presets :-/

**Comment by joschahenningsen** [comment]
Since we have no meaningful way of controlling the aspect ratio and resolution of the presentation input there's not a lot we can do about the combined view. That's why we created the Split-View player in which you can resize the videos however you want:

![image](https://user-images.githubusercontent.com/44805696/211261835-389e8886-8ebb-4fb9-81bc-2efbae36a071.png)

Please leave some feedback, I'd consider this resolved :)

**Comment by A-Sam** [comment]
best for now i think. Until overlay is supported

**Comment by WafaAmr** [comment]
I think the redundant padding in red appears to reduce the overall size of the presentation.

![CleanShot 2023-09-24 at 15 48 15@2x](https://github.com/TUM-Dev/gocast/assets/29930609/0867248d-b6c4-4b73-8fe9-7d460fec26dc)
![CleanShot 2023-09-24 at 15 49 51@2x](https://github.com/TUM-Dev/gocast/assets/29930609/442dbfb9-840c-459c-86f7-387be535fa89)

Edit: I think this padding is only added when the presenter is using an iPad.
