### ISSUE TITLE
Updating the Getting Started Section

### ISSUE THREAD

**Issue by ata-keskin** [joschahenningsen/TUM-Live#419]
The section for initializing a development environment on the README.md file is outdated. This issue is created to track this.

**Comment by joschahenningsen** [comment]
It would probably make getting started easier if we made the database host configurable and default to localhost. Then we could omit the **Setup IPs** step. Do you want to do this here as well?

**Comment by ata-keskin** [comment]
I already rewrote the README.md file and prepared a pull-request. Can we create another issue for this and do it separately?

**Comment by ata-keskin** [comment]
On an unrelated sidenote: going over the Getting Started steps and running pre-commit manually revealed that the file ./worker/edge/edge.go has a regexp which has the quotation marks "", instead of ``, which causes static-check to fail. We should maybe include this in a bugfix? I dont know if creating an issue only for this makes sense.
