### ISSUE TITLE
Edit button for course and stream on their pages

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#424]
When lecturers and admins are on the page of a course (e.g.` /course/2022/S/mycourse`) or stream(e.g. `/w/mycourse/42`) they might want to edit the content. Having a button redirecting them to the appropriate admin page would be nice.

**Comment by ata-keskin** [comment]
I'd like to work on this! I'm assigning it to myself for the time being. If anyone else wants to work on it as well, feel free to message me and I'll look for something else.
