### ISSUE TITLE
Show Lecture Hall for next Lecture on Course Page

### ISSUE THREAD

**Issue by MatthiasReumann** [joschahenningsen/TUM-Live#428]
**Is your feature request related to a problem? Please describe.**
It would be quite nice to know in which lecture hall the next lecture is streamed from. Especially since the UX on TUMLive is much more accessible than on TUMOnline. 

**Describe the solution you'd like**
Display lecture hall name below '_Next Livestream_', '_Now Live_', etc. That way the UI keeps clean and the information in which hall the next lecture takes place can be found with ease.

**Comment by CommanderStorm** [comment]
In desktops this could even fit in next to the current livestreams, as there is a lot of space left :)
![image](https://user-images.githubusercontent.com/26258709/166663456-114cd3ec-4a9c-4e5e-b7e8-659faf61cf90.png)
If you want, you could also link to a roomfinder. https://nav.tum.sexy/view/{room-code}, f.ex. [5602.EG.001](https://nav.tum.sexy/view/5602.EG.001) would such an link.

**Comment by MatthiasReumann** [comment]
> In desktops this could even fit in next to the current livestreams, as there is a lot of space left :)
> ![image](https://user-images.githubusercontent.com/26258709/166663456-114cd3ec-4a9c-4e5e-b7e8-659faf61cf90.png)
> If you want, you could also link to a roomfinder. [https://nav.tum.sexy/view/{room-code}](https://nav.tum.sexy/view/%7Broom-code%7D), f.ex. [5602.EG.001](https://nav.tum.sexy/view/5602.EG.001) would such an link.

Great idea. 💯

**Comment by joschahenningsen** [comment]
We have this for admins now, imo this is enough. If we want we can extend it to all users though.
