### ISSUE TITLE
Different speeds don't work on Firefox mobile

### ISSUE THREAD

**Issue by maribox** [joschahenningsen/TUM-Live#430]
When changing the speed to over 1, it plays faster for a little while, but every few seconds it loads even though the internet speed is fast enough to potentially play at >10x (150mbit). Doesn't happen in Chrome, but a fix would still be nice for the probably ~1000 (2%) people at TUM using Firefox Mobile.
Oddly enough happens more often in 1.25x and 1.5x than 2x. There are also no websites I've ever had this problem with so I assume TUM Live has to be the problem.
Tested in 99.2.0 and 101.0.0-beta.1

**Comment by joschahenningsen** [comment]
Which operating system do you use? Apple tends to come with their own implementation of HLS. From what I read, Firefox started enforcing rather small video buffers, that sounds like a potential cause for this issue, maybe I can override this behavior.

**Comment by maribox** [comment]
I am using Android. MIUI Global 12.5.1 to be exact.

That sounds promising!

**Comment by just-max** [comment]
Same thing for me on mobile Firefox 100.1.1. It looks like the native `video` element interferes with the video.js HLS player. See [video.js](https://videojs.com/guides/setup/#creating-a-player) or [videojs-http-streaming](https://github.com/videojs/http-streaming#getting-started) docs about `video-js` element. After changing all `video` elements to `video-js`, things work fine, is that an acceptable fix? Here is a [MWE](https://gist.github.com/just-max/1bc59fba68cbc0237907ed112bb8153e).
