### ISSUE TITLE
Adaptive Bitrate

### ISSUE THREAD

**Issue by Raupinger** [joschahenningsen/TUM-Live#44]
I think it's obvious that TUM-Live should be as accessible as possible, so offering lower-bitrate streams for people with bad internet connections is something worth discussing. There are of course some potential drawbacks to this which may outweigh the benefits:
- high processing requirements on the server for re-encoding the video stream 
- Added complexity
- @joschahenningsen mentioned something about licensing costs
- time might be better spent on other features

**Comment by joschahenningsen** [comment]
> - high processing requirements on the server for re-encoding the video stream
> - Added complexity
> - time might be better spent on other features

I'm fine with all of these. We'll focus on this.

**Comment by joschahenningsen** [comment]
We are thrilled to announce that adaptive bitrate will come soon™
Additionally we'll most likely implement DVR. That means that you'll be able to sleep an hour more, scroll back to the beginning of the live lecture and watch it in double speed :tada: 

Unfortunately it may take a month or two until we figured out who will pay additional server and licensing costs. But stay tuned!

**Comment by Raupinger** [comment]
Great 🎉

**Comment by joschahenningsen** [comment]
Available in all future streams :)
