### ISSUE TITLE
Descending Order of VODs are not daywise descending

### ISSUE THREAD

**Issue by LadnerJonas** [joschahenningsen/TUM-Live#448]
**Describe the bug**
When visiting the VOD-section of a course, the "desc" order of the VODs is only monthwise descending instead of daywise.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any course overview side with active VODs
2. See VOD-section

**Expected behaviour**
A day-wise descending VOD list. This improves the user/student experience, because most students are going to watch the most recent VOD. When there are a lot of lectures within a month, this issue gets even worse.

**Screenshots**
![image](https://user-images.githubusercontent.com/92096842/167943257-3d2b611e-7607-4cc1-bb62-de9985094ec5.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux 
 - Browser Firefox
 - Version 100 🎉 

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android 11 (stock/Oxygen OS)
 - Browser Google Chrome
 - Version 101

**Comment by just-max** [comment]
Ah so it's not just me. Fixed it in #447 :)

**Comment by LadnerJonas** [comment]
Great that a PR is already in progress. 🚀 
Sorry for only checking the issues for a duplicate.
