### ISSUE TITLE
Feature request: More interoperability with non-web players, like mpv

### ISSUE THREAD

**Issue by Hofmer13** [joschahenningsen/TUM-Live#45]
**Is your feature request related to a problem? Please describe.**
Non web-based media players, like mpv, work very well with the streams displayed at tum live.
They tend to use less memory, can buffer streams, allow fine control of playback speed and even allow to rewind.
Hence, their use would be very popular if they were easy to use.

**Describe the solution you'd like**
- Add a link to the `*.m3u8` file of the stream, so that if you click on it, Firefox can show it's dialogue to download or open with, eg. mpv.
- Add an option to only show the chat of the stream, without the video player.

**Describe alternatives you've considered**
The `*.m3u8` file can probably be gotten from source text, like at live.rbg.tum.de, but that's less convenient.

**Additional context**
No.

**Comment by Raupinger** [comment]
\+ 1 for this

**Comment by joschahenningsen** [comment]
Done. :ok_hand: Chat popout will come soon as well.
