### ISSUE TITLE
VODs not scaled correctly

### ISSUE THREAD

**Issue by Trattue** [joschahenningsen/TUM-Live#46]
**Describe the bug**
When viewing a VOD with 16:9 aspect ratio, the video is scaled to fit the page. With a 4:3 aspect ratio, however, the bottom part of the video may not be visible.

**To Reproduce**
1. Visit a [VOD with 16:9 aspect ratio](https://live.mm.rbg.tum.de/w/absfest/2)
2. Visit a [VOD with 4:3 aspect ratio](https://live.mm.rbg.tum.de/w/test/26)

**Expected behavior**
VODs should be scaled to fit the page correctly.

**Screenshots**
16:9 aspect ratio VOD:
![grafik](https://user-images.githubusercontent.com/63713970/113195042-19aab400-9262-11eb-8ef1-ebebc6e5150f.png)

4:3 aspect ratio VOD:
![Screenshot_2021-03-31 Lasttest Project Code Rush - The Beginnings of Netscape Mozilla TUM Live](https://user-images.githubusercontent.com/63713970/113194859-e10ada80-9261-11eb-9a60-aae06350ec27.png)

**Desktop**
 - Device: 1900x1080 Monitor
 - OS: Windows 10
 - Browser: Firefox 87.0

**Additional context**
Interestingly, the load test stream did fit the page.

**Comment by joschahenningsen** [comment]
The 16:9 version should now be processed and available.This should ofc. be rendered properly even if it's a 4:3 video. It's is on the roadmap along with restyling the chat.
