### ISSUE TITLE
HTTP Method Mismatch in Lecture Description Edit Leads to 404

### ISSUE THREAD

**Issue by just-max** [joschahenningsen/TUM-Live#460]
Route is `POST`:
https://github.com/joschahenningsen/TUM-Live/blob/b260f68171736a595dbc3d4fec57c0abe1340e57/api/courses.go#L48

Client uses `PUT`:
https://github.com/joschahenningsen/TUM-Live/blob/b260f68171736a595dbc3d4fec57c0abe1340e57/web/ts/edit-course.ts#L187

This fails with a 404. Using the same request in cURL but with the method changed to `POST` works fine. This should probably be a `PUT` in both cases, since it is idempotent.

This was broken in #394 by [the look of it](https://github.com/joschahenningsen/TUM-Live/blame/b260f68171736a595dbc3d4fec57c0abe1340e57/api/courses.go#L48) @MatthiasReumann.

Maybe other uses of the API should be reviewed for consistency?

**Comment by joschahenningsen** [comment]
Thanks for reporting, this is the kind of stuff that slips into +- 5000 line PRs :D
