### ISSUE TITLE
Support Panasonic AW-HE40 Cameras

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#466]
Currently we only support axis cameras. I'd like to be able to also control Panasonic AW-HE40 Cameras (get presets, previews, switch presets etc.)

**Comment by joschahenningsen** [comment]
@tizleo something for you?

**Comment by gedw99** [comment]
Suggest SRT 

https://github.com/Haivision/srtgo

in most broadcast quality gear from JVC, Sony, Panasonic and it open standard used to transmit over IP

**Comment by joschahenningsen** [comment]
Thanks for the hint @gedw99 I've actually wanted to use srt for a while now but didn't have a chance to due to vendor lock-in. 

Getting the actual video is not an issue though, we use specialized hardware to get streams via rtsp (among others). This issue aims to allow moving the cameras automatically (e.g. zooming on the blackboard when the stream starts and the lecturer uses the blackboard. A usecase most commonly seen in math classes)

**Comment by joschahenningsen** [comment]
So to be specific, we need to build a client for such cameras http api as specified here: https://eww.pass.panasonic.co.jp/pro-av/support/content/guide/DEF/HE40_UE70_CGI/Supplement_for_Web_Control-UE70E.pdf

**Comment by gedw99** [comment]
@joschahenningsen ok i see.    

https://github.com/krupper/ptz-control gets it done. Just wrap the Node calls
