### ISSUE TITLE
Exposing a lecture's key and server URL via json

### ISSUE THREAD

**Issue by DrMichaelPetter** [joschahenningsen/TUM-Live#468]
**Is your feature request related to a problem? Please describe.**
I am an admin for a streamed lecture, and it is quite tedious to input each streaming key and server URL individually for each lecture anew.

**Describe the solution you'd like**
As an admin of a lecture, I would like to have a custom URI to obtain a list of scheduled streams for a particular lecture with their credentials in a machine readable way, e.g. json . I could read that in an OBS script/plugin , and automatically enter the next streaming credentials.

**Describe alternatives you've considered**
Alternatively I was considering crawling the Webinterface of a lecture by hand which would be possible, but a rather inefficient use of my time.

**Comment by joschahenningsen** [comment]
Possibly also resolved with #124?

**Comment by DrMichaelPetter** [comment]
Yes, that would be optimal.
