### ISSUE TITLE
Display thumbnails when hovering over the timeline

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#472]
**Is your feature request related to a problem? Please describe.**

YouTube and other platforms show a small thumbnail of the video when hovering over the progress bar.

![Peek 2022-05-19 10-53](https://user-images.githubusercontent.com/30267166/169254347-6a8e9ed0-7f90-46d0-875b-d3268586ed23.gif)

This is useful when searching through lectures or when wanting to skip certain parts of lecture.

**Describe the solution you'd like**

Sprites should be generated for every VoD in 5s intervals using https://github.com/flavioribeiro/video-thumbnail-generator.
Then we can fetch the sprites and integrate them in the timeline via https://github.com/phloxic/videojs-sprite-thumbnails

**Describe alternatives you've considered**

Generation of sprites uses a considerable amount of memory, therefore this feature is fairly expensive in term of resources. We could just leave it as it is, but I think it's worth it.

**Comment by joschahenningsen** [comment]
Love the idea! 

> https://github.com/flavioribeiro/video-thumbnail-generator 

Not a fan of including a python (<3.7!) script in the worker. If I get this right, the script exports a frame every n seconds and sticks them together in a grid. Maybe we can implement such an algorithm in go?

> Generation of sprites uses a considerable amount of memory

I just tested the python script. It appears to load a considerable amount of the video into memory, I'm currently exporting frames from the gbs repetitorium and it utilises about 5G (maybe I misconfigured it?) of memory while taking quite some time. ffmpeg is able to export frames within fractions of a second with no memory overhead. I suggest splitting up this task. I'd like to take over re-implementing the thumbnail generation as part of the worker if you want. What do you think? :)

**Comment by joschahenningsen** [comment]
> Sprites should be generated for every VoD in 5s intervals 

I think the interval should be dynamic depending on the length of the video. The gbs rep generated a 50mb image with 600x56.000 pixels :D

**Comment by alexanderstephan** [comment]
> I'd like to take over re-implementing the thumbnail generation as part of the worker if you want. What do you think? :)

We can do that :+1: We could also move it to a repo later in case other people are interested. I guess there must be other people who dislike (old) python...

> I think the interval should be dynamic depending on the length of the video. The gbs rep generated a 50mb image with 600x56.000 pixels :D

That's a good idea, fortunately these really long videos are rare...

**Comment by MatthiasReumann** [comment]
I assume this images have to be stored somewhere, right? Then we could also use these thumbnails for #475.

**Comment by alexanderstephan** [comment]
Yes, that's a really good idea. As Joscha did most of the backend functionality already, I think I can start with the front-end part tomorrow. So the thumbnail feature should hopefully be ready this week.

**Comment by alexanderstephan** [comment]
@MatthiasReumann Maybe we could also enhance the video sections with the thumbnails, like YouTube does e.g. 
![grafik](https://user-images.githubusercontent.com/30267166/169839810-35edfb5c-007d-41c4-8c12-7b7aff47bcb3.png)

**Comment by MatthiasReumann** [comment]
> @MatthiasReumann Maybe we could also enhance the video sections with the thumbnails, like YouTube does e.g.
> ![grafik](https://user-images.githubusercontent.com/30267166/169839810-35edfb5c-007d-41c4-8c12-7b7aff47bcb3.png)

That's exactly what I thought too!
