### ISSUE TITLE
Replay chat in VODs

### ISSUE THREAD

**Issue by Trattue** [joschahenningsen/TUM-Live#49]
**Is your feature request related to a problem? Please describe.**
When watching a VOD, it's useful to be able to see which chat messages were sent during that time in the live stream. For example, the user may want to quickly see answers in chat to questions asked in the stream, or questions asked in chat answered in the stream. Currently, the VOD chat contains a log of all messages sent during the stream.

**Describe the solution you'd like**
I propose the chat to be replayed during the VOD. This could be realized by automatically scrolling the chat log in the client (so the most recent message during the stream is at the bottom, just like a real time chat).

**Describe alternatives you've considered**
Leaving everything as is requires manually scrolling and searching in the chat.

**Comment by joschahenningsen** [comment]
This will definitely come sometime next semester. :+1:
