### ISSUE TITLE
Playback Controlling Shortcuts (Arrow Keys, shift+Comma ...)

### ISSUE THREAD

**Issue by MrStrenggeheim** [joschahenningsen/TUM-Live#491]
I would love to see more *keyboard shortcuts* to control the video playback.
Maybe one could mimic the shortcuts that youtube already uses?
Like some are already implementet (like K=pause, M=mute) but some are missing imo:

key | function 
---|---
<kbd>⇧ Shift</kbd> + <kbd>,</kbd> | inc speed
<kbd>⇧ Shift</kbd> + <kbd>.</kbd> | dec speed
<kbd>→</kbd> | 5 or 10 sec skip
<kbd>←</kbd> | -5 or -10 sec skip
<kbd>↑</kbd> | inc volume
<kbd>↓</kbd> | dec volume
<kbd>0</kbd>, <kbd>1</kbd>, ... | jump within video

**Comment by joschahenningsen** [comment]
This has already been implemented and was merged just 30 minutes ago :D https://github.com/joschahenningsen/TUM-Live/pull/476

You can expect to see it live soon :)
