### ISSUE TITLE
Control Playback Speed of Recordings

### ISSUE THREAD

**Issue by severinsch** [joschahenningsen/TUM-Live#50]
A button for adjusting the playback speed of recordings is a very convenient feature I regularly use on other platforms.
Especially for lectures it is often helpful to be able to watch the recording faster.

**Describe the solution you'd like**
A button opening a small menu to choose from given playback speeds. Ideally located somewhere close to the progress bar, e.g. next to the quality settings button. Ideally in small steps from 1x to maybe even 3x.

**Describe alternatives you've considered**
An alternative would be using a browser extension (like https://github.com/igrigorik/videospeed). [See this github page for more details as to why watching recordings at a higher speed is nice as well.]

**Additional context**
An example from a BigBlueButton recording:
![BBB-recording](https://user-images.githubusercontent.com/70469009/113344079-c5620b80-9317-11eb-9bee-7137726a062c.png)

**Comment by joschahenningsen** [comment]
Totally forgot to add that in. Should be live in a minute or two.
