### ISSUE TITLE
Download Buttons for Recordings

### ISSUE THREAD

**Issue by severinsch** [joschahenningsen/TUM-Live#51]
**Is your feature request related to a problem? Please describe.**
When watching recordings you still need a steady internet connection. Being able to easily download e.g. lecture recordings to watch them on the go without having to rely on mobile connectivity would make the lecture more accessible to people with limited mobile data.

**Describe the solution you'd like**
A simple download feature to easily download recordings. Making the recordings downloadable could be an optional feature so each lecturer can decide if he or she wants the users to be able to download recordings. 

**Describe alternatives you've considered**
Students can (and will) get the .m3u8 link from the site's sourcecode to record and/or download the videos. A feature like this will make this process more convenient. 

**Additional context**
For example the Panopto service used for recordings of some lectures at TUM already offers this feature.

**Comment by joschahenningsen** [comment]
We're considering a download feature that can optionally be enabled by lecturers :+1:

**Comment by joschahenningsen** [comment]
I've implemented this but included a pretty steep rate limit of 250kbps for now until I know how the storage would perform when many folks download their lectures at once. You can try it out on the loadtest.

**Comment by joschahenningsen** [comment]
You should now be able to download lectures _kind of_ fast.
