### ISSUE TITLE
Watching the VoD after marked as watched overwrites "watched"

### ISSUE THREAD

**Issue by corumlumert** [joschahenningsen/TUM-Live#528]
**Is your feature request related to a problem? Please describe.**
I use the feature "mark as watched" a lot, as it is then really easy to keep track of my progress. However, sometimes I have to go back to a single VoD of a lecture, which I already marked as watched, to take a look at something etc. .But watching/loading this VoD again removes the "watched" marker. That I loaded this VoD does not mean in general that I didn't watched it, and mostly I get confused whether I watched it or not.

**Describe the solution you'd like**
I would suggest to completely change this behavior, so that loading a VoD does not overwrite "watched" field, or adding and option into settings so that user can decide if this is wanted.

**Comment by alexanderstephan** [comment]
This is actually not intended behavior, thanks for reporting!
