### ISSUE TITLE
Create thumbnails for existing VoDs

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#536]
https://github.com/joschahenningsen/TUM-Live/pull/478 only works for newly generated VoDs. We should probably create an endpoint in the worker for generating the thumbails for all the existing streams.

**Comment by MatthiasReumann** [comment]
The same is needed for video section images. How about a `(Re-)Generate Thumbnails and Video Section Images` Button?

**Comment by alexanderstephan** [comment]
Sounds good! We could also just write a program that generates them one-by-one, but this would need a lot of resources and energy to do it for every existing VoD.
