### ISSUE TITLE
Use arrow keys to scroll through VoDs list in course view

### ISSUE THREAD

**Issue by fritzrehde** [joschahenningsen/TUM-Live#537]
**Is your feature request related to a problem? Please describe.**
I like navigating websites using the keyboard, but I am forced to use the mouse to scroll up and down in the VoDs tab in a course overview (e.g. https://live.rbg.tum.de/course/2022/S/theo).

**Describe the solution you'd like**
Pressing the up and down keys scrolls up and down in the VoDs tab.

**Comment by joschahenningsen** [comment]
Do you have an example of a website that does this right? Because on my device I can use the tab and arrow keys to navigate the course page just fine (given the vod section has focus)
