### ISSUE TITLE
Behaviour of the Logout/Settings popover menu

### ISSUE THREAD

**Issue by lukaskollmer** [joschahenningsen/TUM-Live#542]
**Describe the bug**
The popover menu that gets shown when you hover over your username in the top-left corner is a bit weird:
- the menu gets presented when you hover over your username
- it gets dismissed when you click your username while it is presented, but if you then click the username again, it won't reappear (which it feels like it should, given that clicking makes it disappear while presented, clicking while not presented should make it appear)
- it only gets dismissed if the cursor is moved out of the popover, but it does not get dismissed if the cursor is moved away from the username without first moving it into the popover (given that hovering above the username makes it appear, ending the hover (by moving the cursor away from the username w/out going through the popover) should also make it disappear again

**To Reproduce**
See above

**Expected behavior**
If some event (like e.g. moving the cursor into some specific area of the web page) makes the popover appear, then the opposite event (like e.g. moving the cursor away from that specific area of the web page) should trigger the opposite action, i.e. make the popover disappear.
(The same goes for dismissing/presenting via a click on the username)

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 102.0.5005.115

**Smartphone (please complete the following information):**
n/a, didn't try

**Additional context**
I realise that this is pedantic and probably not that important to anyone except me, so feel free to ignore.

One more thing: I feel like the order of the "Logout" and "Settings" links should probably be reversed, since that's how most web apps seem to order these actions (i.e., having the Logout link as the very last).

**Comment by just-max** [comment]
The behaviour is also different from that of the buttons on the right (theme and notifications).
