### ISSUE TITLE
Preserve playback speed

### ISSUE THREAD

**Issue by lukaskollmer** [joschahenningsen/TUM-Live#543]
**Is your feature request related to a problem? Please describe.**
Currently, the website remembers my position for individual recordings, but it does not remember the playback speed i had selected.

**Describe the solution you'd like**
The playback speed selected for a recording should be preserved across multiple loads of the web site.

**Describe alternatives you've considered**
Don't do this and keep the current behaviour. It's just one click anyway.

**Additional context**
n/a

**Comment by alexanderstephan** [comment]
That's a nice idea, the way it works right now also makes it rather easy to extend it. We could also probably store things like audio levels and video quality.

**Comment by joschahenningsen** [comment]
audio levels are already persisted, we can just use that code I think :D
