### ISSUE TITLE
Add "Copy HSL URL" button next to each video in course overview

### ISSUE THREAD

**Issue by fritzrehde** [joschahenningsen/TUM-Live#548]
**Is your feature request related to a problem? Please describe.**
I prefer downloading lecture videos and then watching them in mpv. It is a little annoying to have to click on the video in the course overview and have it start auto playing, even though all I need is the HSL url.

**Describe the solution you'd like**
Add the same "Copy HSL URL" button, which can be found in the bottom right once the video starts auto playing, next to the "Mark as watched" button in the course overview.

**Describe alternatives you've considered**
Alternative, but much for complicated: receive HSL links via an RSS feed (possibly for each subject)

**Comment by CommanderStorm** [comment]
Actually a download button is already implemented. 
However the lecturers need to enable it (most dont).

So there are two options:
- Either write an email to your lecturer, why this is a feature you want enabled (bad internet/..)
- use https://github.com/Valentin-Metz/tum_video_scraper or something equivalent 😉
