### ISSUE TITLE
Thumbnails versions mixed up

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#550]
**Describe the bug**
Sometimes the versions of the thumbnails get mixed up. This is somehow related to the latest changes, I think it stopped working after the latest deployment.

Potential issue: https://github.com/joschahenningsen/TUM-Live/blob/ea2913f09ecb143961ec505b337b8959f3a8db0f/model/file.go#L15

**To Reproduce**
1. Go to https://live.rbg.tum.de/w/I2DL/12354/CAM
2. Hover over timeline
3. Observe thumbnails for presentation instead of camera

**Expected behavior**
The thumbnail version should match the stream version.

**Additional context**
The issue can somehow not be reproduced on the testserver. There all version seem to match, see https://test.live.mm.rbg.tum.de/w/airplay/498/CAM

**Comment by joschahenningsen** [comment]
todo: move 	FILETYPE_IMAGE_JPG  to bottom, delete section previews

**Comment by alexanderstephan** [comment]
Another option would be to just migrate the existing thumbnail types to the new logic, so +1 in the database for all thumb types (until yesterday I guess).

**Comment by joschahenningsen** [comment]
That would be even cleaner I suppose.

**Comment by joschahenningsen** [comment]
This can also be tracked in #536 I think
