### ISSUE TITLE
Speicher-Anfrage auf Macbook

### ISSUE THREAD

**Issue by ludwiggr** [joschahenningsen/TUM-Live#569]
Ich werde bei jeder Weiterleitung und jedem Website-Aufruf erneut gefragt, ob ich bis zu 1,2GB lokalen Speicher auf dem Mac freigeben will. Da ich euere Bitcoin-Mining Operation nicht unterstützen will, klicke ich immer nein. 

Das Streamen funktioniert dann auch ohne die 1,2GB lokalen Speicher.

**Comment by alexanderstephan** [comment]
Possibly a Webkit bug, see https://bugs.webkit.org/show_bug.cgi?id=202137. You're using Safari, I guess?

**Comment by joschahenningsen** [comment]
Bitcoin mining, lol 😂

Closed in #551

**Comment by joschahenningsen** [comment]
Am besten einmal den Browser Cache für live.rbg.tum.de löschen, bis #551 wurden da Video Segmente zwischengespeichert.
