### ISSUE TITLE
Media keys shouldn't change the stream/video directly

### ISSUE THREAD

**Issue by Smail** [joschahenningsen/TUM-Live#581]
**Describe the bug**
The media keys, i.e., play/pause, volume up, volume down, etc., currently change the stream *and* the operating system. This means, that when pressing the volume up button, it'll change the volume of the operating system - which is the desired behavior - but also the stream's individual volume, which is the undesired behavior. You can also see this with the play/pause button. It works properly when the stream tab is not focused, but doesn't work when it is focused, i.e., pressing it will execute the command twice, meaning nothing happens and the stream still continues (or stays paused).

**To Reproduce**
* Focus stream tab
* Press the Play/Pause-button or a volume button.

**Expected behavior**
The buttons should not change the stream itself. Let the operating system do its job.

**Desktop:**
 - OS: Windows, Ubuntu
 - Browser: Edge (chromium)

**Comment by CommanderStorm** [comment]
@Smail 
Since you liked #545 ... what is the difference between the two issues?
Could you edit your Issue to make this more clear? 😅

**Comment by Smail** [comment]
Fair point. This issue also includes the play/pause bug, but in hindsight it should've been a comment.
