### ISSUE TITLE
Switch away from"Moin" and make it "Servus" or just hello

### ISSUE THREAD

**Issue by FelixWenzel02** [joschahenningsen/TUM-Live#586]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when i log in on tum.live and realize im beeing greeted by the north german "Moin"

**Describe the solution you'd like**
I want it to say "Servus"

**Describe alternatives you've considered**
it could be a neutral "Hello"

**Comment by MatthiasReumann** [comment]
You actually can change it to `Servus` on your settings page. For that click on `<your name> > Settings`.
