### ISSUE TITLE
Make Branding Customizable

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#607]
If a non-TUM user wants to deploy TUM-Live, they should be able to mount their own branding config into the docker container to change page title, icons etc. 

This includes: 
- [ ] Header Icon
- [ ] Meta information (e.g. page title and description)
- [ ] Service-worker meta information
- [ ] favicon
- [ ] ?

**Comment by CommanderStorm** [comment]
Content for
- [x] [imprint](https://live.rbg.tum.de/imprint)
- [x] [privacy](https://live.rbg.tum.de/privacy)
- [x] [about](https://live.rbg.tum.de/about)

Possibly a way to cusomise the login, but these could also be follow-ups

**Comment by joschahenningsen** [comment]
imprint, privacy statement and about page are already customizable. (Thanks to @MatthiasReumann)

**Comment by MatthiasReumann** [comment]
It would be pretty awesome if it were possible to change primary colors.
