### ISSUE TITLE
15 sec skip backwards

### ISSUE THREAD

**Issue by MG-ng** [joschahenningsen/TUM-Live#62]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to skip back like 10 - 20 seconds. 

**Describe the solution you'd like**
I would like a skip button. 

**Describe alternatives you've considered**
One time, there was a link to only use the native browser player which has such a button. But this link disappeared in my recent recordings. 

**Additional context**
I'm watching the VoD recordings. In my safari browser, there is the option to show native browser controls which have a skip button included but those controls overlap with the site javascript video controls. In fact, they are behind them so I can't use the native skip buttons easily. 

<img width="1087" alt="Bildschirmfoto 2021-04-20 um 18 15 35" src="https://user-images.githubusercontent.com/45321071/115430165-6996ee00-a204-11eb-8dc7-05759b6966a4.png">

**Comment by joschahenningsen** [comment]
Thanks for the request. This is sort of related to #43. I'll add such buttons and keyboard controlls within the next days!

**Comment by joschahenningsen** [comment]
Seek buttons are live, ping me if there are any issues with them!
