### ISSUE TITLE
Up to 3 times speed up

### ISSUE THREAD

**Issue by CROminator** [joschahenningsen/TUM-Live#629]
Hello,
some Profs speak so slowly but clearly that I can understand them easily on 3 times speed up what makes my learning both faster and more focused (BBB allows 3 times speed up so I know how that sounds). I would be very thankful if you could consider implementing this.

Kind regards

**Comment by joschahenningsen** [comment]
You can click on your name in the header, navigate to settings and enable the playback speeds you want to use :) 
![image](https://user-images.githubusercontent.com/44805696/182809511-0ab34486-e2b6-4975-918a-56dde4516f61.png)
![image](https://user-images.githubusercontent.com/44805696/182809599-d5f96805-3c8a-487f-8d25-a1be7a16c0ef.png)

**Comment by CROminator** [comment]
Hello Joscha, 
thank you for the fast answer :D.
