### ISSUE TITLE
Enhancement: Include Timestamp in URL

### ISSUE THREAD

**Issue by just-max** [joschahenningsen/TUM-Live#632]
It would be nice to be able to share a URL to a stream that includes a timestamp. For example, instead of saying "go watch https://live.rbg.tum.de/w/gad/12474 starting at 14:58 :sheep:" you could just share the link https://live.rbg.tum.de/w/gad/12474?t=898. Then, playing the stream would automatically seek to the given timestamp. Adding a "share" button that (optionally) includes the timestamp would be an additional nice-to-have. (YouTube does this for example)

**Comment by MatthiasReumann** [comment]
Great idea. Will look into it.
