### ISSUE TITLE
Timeline Thumbnails showing start of the video

### ISSUE THREAD

**Issue by furkan-celik** [joschahenningsen/TUM-Live#640]
**Describe the bug**
When I watch the VoD in the link https://live.rbg.tum.de/w/MLfGaSD/13180 I can't view correct thumbnails on the timeline. It shows start of the video for every timestep.

It is also showing camera view instead of presentation + camera but this bug is already mentioned in #550 

**To Reproduce**
1. Login
2. Start to watch the video
3. Inspect timeline

**Expected behavior**
I would expect to see thumbnails for at least a near point, not the start of the video.

**Screenshots**
![Screenshot (9)](https://user-images.githubusercontent.com/6495679/184669562-c9898810-f54c-43cc-a252-89ee056749c5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 104.0.5112.81 64 bit

**Comment by alexanderstephan** [comment]
Thanks for bringing this up again. I think there was some issue in the database regarding the interval. This happened when the feature was initially shipped. I am currently finishing https://github.com/joschahenningsen/TUM-Live/pull/582, which should also fix this. I'll check back if this still is a problem after regenerating the thumbnails.

**Comment by joschahenningsen** [comment]
let's track this in #536
