### ISSUE TITLE
Allow LaTeX snippets in chat

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#679]
Unsure if this is really something we **should** implement depending on the complexity of a potential solution, but messages like this:

![image](https://user-images.githubusercontent.com/44805696/191711023-4b18b13b-424e-491a-8c25-09690cf27d1d.png)

Would look much better if we allowed creating latex snippets. IMO this would require a more sophisticated chat input which I'm not sure we actually want.

**Comment by alexanderstephan** [comment]
I implemented this once with https://katex.org/, worked pretty well. Should be quite straight forward to add it.

**Comment by joschahenningsen** [comment]
Nice, so that renders the snippets in the frontend, right?

**Comment by alexanderstephan** [comment]
Yes, it renders in the browser, but it did feel pretty light weight.

**Comment by alexanderstephan** [comment]
<img width="181" alt="grafik" src="https://user-images.githubusercontent.com/30267166/192094512-067a6339-4b5c-4823-98e3-3edc53d3b210.png">
Must be fast then 😂

**Comment by alexanderstephan** [comment]
~~https://pkg.go.dev/gopkg.in/oi-archive/blackfriday.v2#section-readme Technically, blackfriday already supports MathJax and MathJax supports LaTeX like syntax afaik. That would be an alternative, I suppose.~~
Nevermind, just a weird old repo.
