### ISSUE TITLE
Contrast on Course Creation

### ISSUE THREAD

**Issue by CommanderStorm** [joschahenningsen/TUM-Live#708]
**Describe the bug**
In Darkmode, this text fields are less readable:
![image](https://user-images.githubusercontent.com/26258709/194562579-df288d9c-e8fa-4999-9dc5-49a6ff16c1b7.png)

**To Reproduce**
1. Go to Admin
2. Click on Create Course
3. Type into the field
4. See white on white text

**Expected behavior**
A better contrast

**Screenshots**
Whitemode:
![image](https://user-images.githubusercontent.com/26258709/194562998-dd6d2638-1153-43c3-8a2b-add78639a1d6.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version latest

**Comment by CommanderStorm** [comment]
Note that I have not checked out PRs like https://github.com/joschahenningsen/TUM-Live/pull/610 if they fix the issue

**Comment by joschahenningsen** [comment]
Yes this was fixed
