### ISSUE TITLE
Invalid Link to docs

### ISSUE THREAD

**Issue by CommanderStorm** [joschahenningsen/TUM-Live#709]
**Describe the bug**
I have found an invalid link to the docs

**To Reproduce**
1. Go to
    ![image](https://user-images.githubusercontent.com/26258709/194564022-5e1a7b1f-f80c-4bd4-a217-13f310b658f2.png) 
2. Click on 'here'
3. See 
    ![image](https://user-images.githubusercontent.com/26258709/194564127-7c398fdd-0bd7-44f3-baab-07a337ff9ffc.png)

**Expected behavior**
No privacy error

**Additional context**
https://docs.live.mm.rbg.tum.de or https://docs.live.rbg.tum.de don't seem reachable

**Comment by alexanderstephan** [comment]
@joschahenningsen I guess we can close this as https://docs.live.rbg.tum.de/ is reachable again?

**Comment by joschahenningsen** [comment]
Yup, still needs content, but this should be closeable…
