### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by CommanderStorm** [joschahenningsen/TUM-Live#711]
**Is your feature request related to a problem? Please describe.**
I think, that currently the plain TUM logo is a bit plain and would like to discuss this.

**Describe the solution you'd like**
A more distinct Logo could open us up to making stickers/ other merch :wink:
As a starting point, what do you think about this Logo?
![TL](https://user-images.githubusercontent.com/26258709/194715409-d397999c-9d81-44f3-9696-cfcedcc5bc69.svg)
[TUMlive.svg](https://user-images.githubusercontent.com/26258709/194715305-495f3f98-10c5-401c-a096-76fe5a7e93c3.png)
[TUMlive.afdesign.zip](https://github.com/joschahenningsen/TUM-Live/files/9739641/TUMlive.afdesign.zip)

**Describe alternatives you've considered**
Sticking to the current logo is also fine.

**Comment by 0ql** [comment]
Looks Good!


![image](https://user-images.githubusercontent.com/45464816/194716457-66a1113a-e037-445a-95ed-f3a2bea2bbbe.png)
![image](https://user-images.githubusercontent.com/45464816/194716661-de3cdd58-c6e4-4bda-a4ba-cfc7943273a7.png)
![image](https://user-images.githubusercontent.com/45464816/194716691-e000e701-4dff-4744-93ff-b1bbaa208115.png)

**Comment by joschahenningsen** [comment]
I really like the logo you provided! 

![image](https://user-images.githubusercontent.com/44805696/194727234-5f973cc2-b56e-4f49-8cd5-a165a2e208ec.png)

Considering that it will be quite small when displayed in the header, the edges and padding of the `live` text might be a little to sharp and small. Also a simpler version where the red box is just a dot might look cool as a favicon?

**Comment by joschahenningsen** [comment]
I noticed that parts of the svg are just a base64 endoded png, this might be something we could also tackle.

**Comment by joschahenningsen** [comment]
Also, the red of the logo and live indicator should match, I don't think it makes a huge difference which to go forward with.

**Comment by joschahenningsen** [comment]
@0ql looks good as well! Though I probably wouldn't go for a gradient

**Comment by CommanderStorm** [comment]
> Also, the red of the logo and live indicator should match, I don't think it makes a huge difference which to go forward with.

hmm…
I could not find a color for this in  [/web/assets/css/main.css](https://github.com/joschahenningsen/TUM-Live/blob/dev/web/assets/css/main.css)
and don't find a colour/icon matching the description in [/web/assets/css/icons.css](https://github.com/joschahenningsen/TUM-Live/blob/dev/web/assets/css/icons.css)

is the mentioned colour the same red as here:
![image](https://user-images.githubusercontent.com/26258709/194773794-6b8a3c7d-458a-473a-97b2-11abb5183bc8.png)

Otherwise: Could you point me to the right colour?

**Comment by MatthiasReumann** [comment]
> > Also, the red of the logo and live indicator should match, I don't think it makes a huge difference which to go forward with.
> 
> hmm… I could not find a color for this in [/web/assets/css/main.css](https://github.com/joschahenningsen/TUM-Live/blob/dev/web/assets/css/main.css) and don't find a colour/icon matching the description in [/web/assets/css/icons.css](https://github.com/joschahenningsen/TUM-Live/blob/dev/web/assets/css/icons.css)
> 
> is the mentioned colour the same red as here: ![image](https://user-images.githubusercontent.com/26258709/194773794-6b8a3c7d-458a-473a-97b2-11abb5183bc8.png)
> 
> Otherwise: Could you point me to the right colour?

<img src ="https://singlecolorimage.com/get/e3342f/32x32">

Hex: `#e3342f`
RGB `227, 52, 47`

**Comment by joschahenningsen** [comment]
The little text next to a Livestream on the start page has the background `red-800` https://tailwindcss.com/docs/background-color
![image](https://user-images.githubusercontent.com/44805696/194819354-a6e03380-73f3-4b82-bf41-1ab8ea252278.png)

**Comment by CommanderStorm** [comment]
Foremost, thanks for being patient, the beginning of the semester is always stressful…

Here are the updated drafts (I have worked on spacing, font and integrated the colours)

Logo:
<img src="https://user-images.githubusercontent.com/26258709/196943237-990a7d7b-4888-409b-90fa-3be9e074d98c.svg" width="50%">

Favoticon (note, that this is slightly modified 😜):
- 32*32px:
<img src="https://user-images.githubusercontent.com/26258709/196943290-d3f5102c-37a9-4cda-8b37-c371eac33d9c.svg" width="32px">

- 16*16px:
<img src="https://user-images.githubusercontent.com/26258709/196943290-d3f5102c-37a9-4cda-8b37-c371eac33d9c.svg" width="16px">

pngs+affinity+svgs:
[TUMlive.zip](https://github.com/joschahenningsen/TUM-Live/files/9829746/TUMlive.zip)

**Comment by 0ql** [comment]
I could create a PR adding the new logo, if it's final?

**Comment by joschahenningsen** [comment]
No need, the logo can be configured without any changes to the code. We'll
do a trial run with these. Love them ☺️

**Comment by CommanderStorm** [comment]
> We'll do a trial run with these.

Were there some Problems you encountered?
Is there something I should fix?

**Comment by joschahenningsen** [comment]
Deployed the new icon. Not sure if the webapp has the right one already. If not this needs to be editable as well.
