### ISSUE TITLE
My internet connection is quite slow, even with a ethernet cable it results in unstable video.

### ISSUE THREAD

**Issue by Zuced** [joschahenningsen/TUM-Live#726]

**Comment by joschahenningsen** [comment]
We currently don't transcode (all) our videos into multiple resolutions as this produces a very high load on our servers.

To make sure the network bandwidth really is your problem, can you please send the results of a speedtest (e.g. speedtest.net) and tell us if video on demands can be played back?

**Comment by Zuced** [comment]
Hello, 
attached are my Speedtest per Speedtest.net and a screenshot of the Video Stats on RGB. Normally the MBit/s is around 0-3 mb, but mostly 0 or 1 mb on the RGB. However I have been noticing huge spikes and slows in MBit/s on the Video Stats. My Speedtest Results also vary quite harshly, sometimes 2-3 MB/s sometimes 11 MB/s. Playback on a recorded video works fine without stuttering, but the problemmakers are the live streams and the currently streamed playbacks they interrupt every few seconds. 
PS: Maybe Vodafone is at fault and the problem is only temporary.
![Speedtest](https://user-images.githubusercontent.com/109238474/196492306-d98769e8-027c-4fb7-8694-f20e9de12614.PNG)
![RGBLiveStream](https://user-images.githubusercontent.com/109238474/196492329-bc6b20c1-cdec-4361-b997-e560674e3aec.PNG)

**Comment by joschahenningsen** [comment]
Can you try clicking the `Beta` button below a livestream and seek back a few seconds? Your browser might be able to use the extra buffer to compensate for the unstable/slow network connection.

**Comment by joschahenningsen** [comment]
Closed due to lack of feedback.
