### ISSUE TITLE
Approving chat messages removes the complete chat for a few seconds

### ISSUE THREAD

**Issue by Jojaa350** [joschahenningsen/TUM-Live#734]
**Describe the bug**
As an admin, whenever I approve a chat message during a livestream, all chat messages disappear for a few seconds. They usually reappear after ½ to 10 seconds, but sometimes they never reappear again until the site is reloaded (in one case, new chat messages appeared but all other messages remained lost until reloaded).
Disturbingly, the messages also were lost for all other viewers, with them reappearing at a different times for everyone.

**To Reproduce**
1. Create and start a livestream
2. Enter a chat message as a regular user (so that it isn't approved automatically)
3. Approve message as an admin

**Desktop (please complete the following information):**
 - OS: Happend for Windows (10), Ubuntu (20.04) and MacOS (version unknown)
 - Browser: all Firefox (mine is 105.0.1)

**Comment by joschahenningsen** [comment]
**Very** odd, I'm looking into it and hope to resolve this until next week.

**Comment by joschahenningsen** [comment]
Currently when approving a message it is not simply send to the clients. Instead the clients get notified to reload **all** messages which is essentially a DoS when there are 500+ viewers trying to get all messages, likes, replies, etc. at the same second.
