### ISSUE TITLE
`Live now` vs `Live`

### ISSUE THREAD

**Issue by CommanderStorm** [joschahenningsen/TUM-Live#737]
**Describe the bug**
For indicating to users, that something is live there are two types of iconographys

**To Reproduce**
1. see `Live` (in red bubble) vs `Live now` (without bubble) 
![Screenshot_20221021_140036_Chrome](https://user-images.githubusercontent.com/26258709/197206042-d3a20715-0adc-4acb-a83f-3199c7182d66.jpg)

**Expected behavior**
Since both are live, both should get the red bubble

**Desktop (please complete the following information):**
 - OS: linux
 - Browser chrome
 - Version latest

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S53
 - OS: android
 - Browser chrome
 - Version latest

**Comment by joschahenningsen** [comment]
The streams themselves are marked as `Live` whereas the courses that are currently live don't have information about the date of their next livestream (so it says `currently live` instead). Not sure how we should make this clear but imo having the red `live` bubble next to the course as well might be confusing and lead to folks navigating to the course when they want to open the stream.

**Comment by CommanderStorm** [comment]
Honestly, I was pretty confused when I was unable to find the livestream in the `Active Livestream` Section.
Note, that information about the next livestream is not an issue, as they are avaliable here:
![image](https://user-images.githubusercontent.com/26258709/197330103-388a17f7-b26a-44a7-8f51-f31649ce858f.png)

**Comment by CommanderStorm** [comment]
Note that putting the Live badge on this course (maybe without the `until xx:xx`, if not possible) would less confusing imo
