### ISSUE TITLE
Faulty redirect to start page after deletion of an admin on course page

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#738]
**Describe the bug**

When deleting an admin from a course page the deletion causes a faulty redirect.

**To Reproduce**

1. Go to a course page
2. Add an admin
3. Delete it
4. Get redirected to the start page

**Expected behavior**

The page should stay the same, ideally not even reload.

**Screenshots**
![Peek 2022-10-21 21-41](https://user-images.githubusercontent.com/30267166/197276622-3a3ca039-ceb0-4bc9-a071-50e933e50659.gif)

**Desktop (please complete the following information):**
 - OS: Manjaro GNOME
 - Browser: Firefox 105.0.3

**Comment by alexanderstephan** [comment]
Seems to be not a problem on dev, just on the branch I've accidentially checked out.

**Comment by joschahenningsen** [comment]
Looks like this happens because `admin` removed themselve from the course admin list. As they are not an admin now, staying on the course administration page doesn't make sense for them.

**Comment by 0ql** [comment]
So this is unintended intended behavior? Also, I can't reproduce this issue as it wouldn't let me remove the last admin.

**Comment by joschahenningsen** [comment]
This behavior is intended imo

**Comment by alexanderstephan** [comment]
I mean this case is kinda weird since I added myself (admin rights in this case). As an admin I, of course, don't need to add myself here. But nonetheless I should able to see and probably stay on the course page. This is really more of an edge case. Maybe we should just prohibit adding admin users as lecturers for a course?
I think this is fine for the PR, but possibly general edge case.
