### ISSUE TITLE
Add real-time total viewer count

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#749]
**Is your feature request related to a problem? Please describe.**
It would be cool to be able to access the total viewer count (the sum of all viewers over all streams) in real time.

**Describe the solution you'd like**
Display this number somewhere on the site e.g. the start page. Additionally, there could be an endpoint that serves the value. This could then be used with an external dashboard, which e.g. could be displayed on a display in RBG office.

**Describe the alternatives you considered**
We could send all the viewer counts to an external entity and sum it there, but that does not really make sense to me.

**Comment by joschahenningsen** [comment]
This can be exported from influxdb.
