### ISSUE TITLE
Watch page misalignment on smaller screen sizes.

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#754]
**Describe the bug**

The lecture hall shifts over the video on smaller screen sizes. It also overlays the chat which has a weird scroll behavior. Maybe some of this intended? I was not sure as it looked kinda off, so I wanted to mention it here.

**To Reproduce**
1. Go any livestream with lecture hall presets and chat
2. Reduce size of window e.g. to `828`x`753`
3. Scroll down to bottom
4. Observe stated behavior.

**Expected behavior**
All settings appear below the video. The video also does not overlay the chat when scrolling down.

**Screenshots**

![Peek 2022-10-29 00-12](https://user-images.githubusercontent.com/30267166/198741644-85d1a32f-e465-4823-a19c-84d9a40bf2bd.gif)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser Firefox
 - Version 105.0.3 (64-Bit)

**Comment by MatthiasReumann** [comment]
The preset issue should be solved after merging #745. There was a minor issue with the `order` property of the flex-box.

That the video always stays on top is something that YouTube does too. I kinda liked it that way but we could change it back to normal behaviour. Nevertheless, the mobile version still needs some love.

**Comment by alexanderstephan** [comment]
Seems to be fixed for a while now. :+1:
