### ISSUE TITLE
Cinema mode

### ISSUE THREAD

**Issue by N0W0RK** [joschahenningsen/TUM-Live#77]
I use Tum Live on a widescreen Monitor and therefore use it next to other windows (e.g. Slides etc.). When resizing the window above a certain size, the video player ist set to 66% of the window width. This leads to unused screen real estate, that has to be covered by overlaping windows and would cover other windows, if the video has to be stopped or adjusted.

A good solution imo would be a "cinema mode" button that leads to the video beeing displayed over the full width/heigth of the window.

**Comment by joschahenningsen** [comment]
I added a big picture mode and would love if you'd let me know when there is anything not quite satisfying about it yet :)

**Comment by N0W0RK** [comment]
Works great, thnaks
