### ISSUE TITLE
Add Course via TUMOnline is Broken

### ISSUE THREAD

**Issue by CommanderStorm** [joschahenningsen/TUM-Live#775]
**Describe the bug**
Currently, the option to easily import Courses from TUMonline is broken

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Add course
2. Search something
3. Nothing happens, for example <https://live.rbg.tum.de/api/searchCourse?q=e> always returns `[]`

**Expected behaviour**
Something happens

**Screenshots**
![image](https://user-images.githubusercontent.com/26258709/199361930-c4268195-cc94-4cfb-b7c1-0ed8ca65e36c.png)

**Additional context**
This is very probable a backend issue, as 
- the fetches come back empty and
- TUMOnline is not down (at least it does not seem like it is..)

**Comment by CommanderStorm** [comment]
Likely related commit: https://github.com/joschahenningsen/TUM-Live/commit/39c4e37ef18addd7a89833b8350f9088b6e0d370

**Comment by joschahenningsen** [comment]
It doesn't seem to be broken, this is just a relatively new feature which was deployed a few days ago and there is a cronjob fetching all courses in tum online once a week (wednesday at 3:00 AM). So currently there are no courses in our database yet :(
Also, the search is a 'stupid' fulltext sql search, so you'll only get results after typing a full word. E.g. 'Einführung'.


Do you need me to create a course?

**Comment by CommanderStorm** [comment]
No, waiting until in a few hours is fine.

**Comment by joschahenningsen** [comment]
After fixing something in our configuration this should now work as expected 
![image](https://user-images.githubusercontent.com/44805696/199419590-fdaa69f1-0c74-4e6f-bd5f-6d89f99dd0ce.png)

**Comment by CommanderStorm** [comment]
Maybe adding something in this line would prevent confusions on the lecturers side in the future would be benefitial.
Also: you only seem to match on `name`. Is that intentional? If yes, please communicate this, to prevent other lecturers being confused. The "Number" `FVVSVV--MA` should for example also be an available input 😉 

> Also, the search is a 'stupid' fulltext sql search, so you'll only get results after typing a full word. E.g. 'Einführung'.
