### ISSUE TITLE
Spacebar press results in last action instead of play\pause

### ISSUE THREAD

**Issue by Vozf** [joschahenningsen/TUM-Live#776]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When I press spacebar I want to always invoke play\pause action, but instead last action is performed(enter full screen mode, mute\unmute or any other player action including play\pause)
**Describe alternatives you've considered**

**Additional context**

**Comment by just-max** [comment]
This behaviour is intentional for accessibility, see https://github.com/joschahenningsen/TUM-Live/issues/521#issuecomment-1153300679.

Instead, pressing `k` always pauses the player (press `?` or possibly `shift+?` to see the full list of shortcuts).

**Comment by Vozf** [comment]
Well basically any other player including youtube vimeo and what so not has spacebar to play\pause and has other instruments for accessibility. Do you believe that youtube is not accessible?

**Comment by just-max** [comment]
Please read the linked issue thread, it provides rationale. We *do* have `space` to play/pause, but activating the currently selected video control (fullscreen, mute, ...) takes priority. This is *exactly* the same behaviour as Vimeo. YouTube is slightly different in that video controls only take priority if they were selected with the keybord (`tab`).

**Comment by Vozf** [comment]
Yeah, you're right vimeo actually has this behavior. What is wrong with following youtube and activating space for nonplay after tab?

**Comment by just-max** [comment]
There's nothing wrong with it. It's just a non-trivial feature to integrate properly with VideoJS (VideoJS currently passes the keyboard presses to our handler, and simply doesn't pass them if they activate controls). Since `k` always works, I didn't really think it was necessary, either.

**Comment by Vozf** [comment]
Thanks for clarification. I see your points. I hope you will consider doing\research doing it Youtube way as in my opinion people mostly expect space to play\pause. I'll close this issue to avoid duplicates

**Comment by just-max** [comment]
I prefer YouTube's behaviour too :/ If I see a straightforward way to do it, I could add it, but it just wasn't really a priority.

**Comment by Vozf** [comment]
I've did some superficial search and found this links. Maybe you'll find anything useful there.
https://stackoverflow.com/questions/64063002/why-videojs-toggles-fullscreen-on-spacebar-press-insted-of-toggling-play-pause
https://medium.com/@agreenb/thinkster-io-video-pause-with-spacebar-ef8508fe6ffb
https://github.com/ctd1500/videojs-hotkeys/blob/master/README.md
https://stackoverflow.com/questions/29918688/video-js-playtoggle-event-conflict
