### ISSUE TITLE
Increase Chat character limit

### ISSUE THREAD

**Issue by Jojaa350** [joschahenningsen/TUM-Live#778]
I've run into the character limit of 300 characters per chat message fairly frequently. It allows for maybe two to three sentences, which is simply too short to answer any question in depth. I'd consider a limit of at least 1000 characters the bare minimum.

Can we increase it? Can we at least exclude admins from it? Or could we even allow the course admins to set the limit for each course individually?

**Comment by joschahenningsen** [comment]
+1 The limit will likely be increased drastically in #774

**Comment by JosefSchoenberger** [comment]
While #774 remains a draft, could we just do this until the beginning of the winter semester?

**Comment by alexanderstephan** [comment]
@joschahenningsen We should also remove `You are sending messages too fast. Please wait a bit.` for moderators and admins at this point.
