### ISSUE TITLE
Smaller clickable area of the course link

### ISSUE THREAD

**Issue by alexandersteinhauer** [joschahenningsen/TUM-Live#78]
Sometimes I accidentally get thrown back into the course menu, because I click under the video to defocus a context menu when configuring video playback. As this also erases the timestamp, this is rather annoying.
As seen in the screenshot below, the clickable area of the href is way too big.
Purely visually, the area on the right shouldn't be clickable.

I would suggest to make the clickable area just as long as the text itself.

![grafik](https://user-images.githubusercontent.com/40439946/120169601-6a0da600-c200-11eb-9507-1c28c5db22ff.png)

**Comment by joschahenningsen** [comment]
thanks, will be deployed after the grvns lecture :+1:
