### ISSUE TITLE
Moderate replies

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#780]
**Is your feature request related to a problem? Please describe.**
When the moderated chat is enabled it should be also possible to accept or decline replies. Right now every reply shows up instantly. Marking a reply solved is probably not needed.

**Describe the solution you'd like**
Same approval procedure as for normal messages, just also extended to replies.

**Comment by joschahenningsen** [comment]
This has been implemented a while back.
