### ISSUE TITLE
Cannot cancel creation of pull: Broken close button

### ISSUE THREAD

**Issue by Jojaa350** [joschahenningsen/TUM-Live#783]
**Describe the bug**
During creation of a poll during a livestream, the close-button on the top right of the poll-creation-form is currently broken, it does not close the form.

**To Reproduce**
1. Open stream
2. Be moderator
3. Click on “New Poll”
4. In the new form, click the X on the top right
5. Nothing happens
6. Be annoyed. ;-P

**Expected behavior**
The form should close.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/39162942/201497712-18c1b7b0-a1cc-4b3b-b4ad-d7281b44d371.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1
 - Browser: Firefox 106.0.3 (64-Bit)

**Additional context**
There is no output on the console.

**Comment by MatthiasReumann** [comment]
Thanks for creating the issue! 

As a temporary solution you can close the dialog by clicking the `NEW POLL` button again. Sorry for the inconvenience. 😕
