### ISSUE TITLE
Remove server messages

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#793]
**Describe the problem**
The server sends messages to the chat right now such as:
1. `Welcome to the chatroom! Please be nice to each other and stay on topic if you want this feature to stay active.`
2. `The broadcaster disabled anonymous messaging for this stream.`

I would argue that this is not needed anymore. The chat can be moderated and was never really abused from my experience.
Also, people should be able to see whether they can send anonymous messages by the icon. I don't think it is necessary to announce this to users as I would expect the default to be not anonymous.

These server messages cause sometimes weird behavior e.g. it appears as if there was a new message sent when watching a stream. Furthermore, in case of disconnects these messages can stack up which looks rather ugly.

**Comment by joschahenningsen** [comment]
Agreed 👍

**Comment by joschahenningsen** [comment]
> and was never really abused from my experience.

It was heavily abused once, I can send you the log sometime, it's hilarious 😆

**Comment by alexanderstephan** [comment]
> > and was never really abused from my experience.
> 
> It was heavily abused once, I can send you the log sometime, it's hilarious laughing

Definitely interested :joy: I  saw some sites having a pop-up where people have to mark a checkbox that they accept the chat rules, but I personally find that kinda annoying.
