### ISSUE TITLE
Picture in picture not being available in webapp

### ISSUE THREAD

**Issue by CommanderStorm** [joschahenningsen/TUM-Live#797]
**Describe the bug**
When looking at a lecture in the webapp, PIP does not create an pop up

**To Reproduce**
1. Install as webapp
2. Click on picture in picture 
4. See ![Screenshot_20221123_085434_Chrome.jpg](https://user-images.githubusercontent.com/26258709/203496180-576d8cd9-5a4b-4538-89dc-603fe222d4eb.jpg)

**Expected behavior**
A PIP

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy S54
 - OS: Andoid 12
 - Browser Chrome 
 - Version latest

**Additional context**
Not a big issue as people using pip and a webapp are probably small.

**Comment by joschahenningsen** [comment]
Works fine for me. How about you @alexanderstephan @mono424 @MatthiasReumann?

**Comment by alexanderstephan** [comment]
Works fine for me on iOS 16.0.3. Possibly, it has already been resolved by an update
@CommanderStorm Can you confirm this is still an issue?

**Comment by mono424** [comment]
Works fine for me too: Android 13 on a Pixel6 ☺️

**Comment by CommanderStorm** [comment]
Can confirm, works
