### ISSUE TITLE
VoD Upload Broken for Missing Start Date and Time

### ISSUE THREAD

**Issue by COM8** [joschahenningsen/TUM-Live#798]
**Describe the bug**
I would like to upload a lecture VoD, but when I do so I just get the "Something went wrong." text.

![image](https://user-images.githubusercontent.com/11741404/203499997-eb608e3b-d674-402b-9d52-da59b3921d90.png)

**To Reproduce**
1. Go to Course Administration
2. Click on `VoD Upload`.
3. Set a lecture title
4. Add a video file.
5. Click on `Create Lecture`
6. You get "Something went wrong."

Example Video:

https://user-images.githubusercontent.com/11741404/203501276-08b6e7f6-da65-49d7-b385-78444858f758.mp4

**Expected behavior**
The VoD upload should be successful.

**Desktop:**
 - OS: Fedora 37
 - Browser Firefox
 - Version 106.0.4 (64-bit)

**Additional context**
The video that should be uploaded:

https://user-images.githubusercontent.com/11741404/203501613-8db6942b-4b19-408d-b540-0a5c0bf816f3.mp4

**Comment by joschahenningsen** [comment]
I  think we need to add some indication about the time being required or set the current time as default.

**Comment by CommanderStorm** [comment]
@COM8 Nice video btw. Really enjoyed that Hanna Montanna joke at the start 😄
