### ISSUE TITLE
Spellchecking in chat message input field

### ISSUE THREAD

**Issue by Jojaa350** [joschahenningsen/TUM-Live#810]
**Is your feature request related to a problem? Please describe.**
Typos and simple misspellings are common for everybody.

**Describe the solution you'd like**
Many websites use the spellchecker feature of the browser. It is not enabled for the input field of chat messages.

I'm no expert in HTML, but maybe the [HTML `spellcheck` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck) could be useful? [Firefox only enables the spellchecker on multiline input fields per default.](https://kb.mozillazine.org/Layout.spellcheckDefault)

**Comment by joschahenningsen** [comment]
Sure good idea :+1:
