### ISSUE TITLE
Record from browser

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#838]
**Is your feature request related to a problem? Please describe.**
Modern browsers support sharing screen and camera. This can be used to record a lecture as well. We should support this to overcome the hurdle of installing and learning software like obs 

**Additional context**
@CommanderStorm in case someone asks: this is a wip.

**Comment by CommanderStorm** [comment]
For other people: I am talking about a feature like https://opencast.org/features/ has.
See https://studio.opencast.org/ for further details
