### ISSUE TITLE
Video embedding no longer possible

### ISSUE THREAD

**Issue by Strohgelaender** [joschahenningsen/TUM-Live#844]
**Describe the bug**
We use the `video_only=1` option to embed live streams and lecture recordings into Artemis. With the most recent version, this is no longer possible due to a TypeError:
![grafik](https://user-images.githubusercontent.com/26540346/206914953-29de9ffb-5348-45ef-8bb0-679075fdb4a3.png)
![grafik](https://user-images.githubusercontent.com/26540346/206914973-1abab8ec-0086-4e2b-b99d-1f267720c4a1.png)

**To Reproduce**
1. Visit a recording with `video_only` set to 1, e.g. https://live.rbg.tum.de/w/itp22/25046?video_only=1
2. The video should be playable, but it is not.

**Expected behavior**
I can watch the lecture recording.

**Screenshots**
see above

This error was reported by multiple students and occurs independently of used systems.

**Comment by joschahenningsen** [comment]
Thanks for the report! Fixing this by tomorrow.

**Comment by joschahenningsen** [comment]
Fixed. Sorry!
