### ISSUE TITLE
Beta Stream: Switching views does not save the current time

### ISSUE THREAD

**Issue by LadnerJonas** [joschahenningsen/TUM-Live#847]
**Describe the bug**
Switching views while using the beta stream does not save the current time.
**To Reproduce**
1. Go to current live stream
2. Activate beta stream
3. Skip -10min from the current live stream time
4. Switch to another view

**Expected behavior**
The current time (e.g. -10min) should be saved and the stream should continue just like before the view change.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux (based on Arch Linux)
 - Browser Firefox
 - Version 108

**Comment by saydemr** [comment]
I can reproduce the same issue on Windows 11, TUM-Live Chrome application. Switching between combined view and split view does not save the current time.
