### ISSUE TITLE
Un-hide Courses

### ISSUE THREAD

**Issue by jpbernius** [joschahenningsen/TUM-Live#85]
**Describe the bug**
By mistake, I did hide a course on the Start page (on iPad). At the bottom of the list, it says "1 hidden course". There is no way to un-hide the course and regain access.

**To Reproduce**
1. Go to 'live.mm.rbg.tum.de' (on iPad)
2. Tap on a course in the list
3. Click on the 👁️ icon in front of the course name.
4. Find "1 hidden course" message
5. Try to regain access
6. Cry

**Expected behavior**
I expect to expand the list of hidden courses and in-hide individual courses as needed.

**Tablet:**
 - Device: iPad Pro (11-inch)
 - OS: iPadOS 14.6
 - Browser: Safari

**Comment by joschahenningsen** [comment]
Thanks for letting me know, 
I don't have an iPad to reproduce this and used my phone for testing which seems to implement different touch behaviours with hoverable elements. I'll fix this. In the meantime you can clear your LocalStorage :)

**Comment by joschahenningsen** [comment]
Also if you want, you can send a screenshot of the website, I'm coursious how it __actually__ looks on iPads
