### ISSUE TITLE
[critical] Chat broken in many ways

### ISSUE THREAD

**Issue by Jojaa350** [joschahenningsen/TUM-Live#875]
The chat seems to be fundamentally broken. ~~People were asking questions as anonymous, although that is not allowed in the course settings.~~ I cannot approve, resolve, delete or reply to messages. I can only sometimes write new messages, which aren't approved by default and are display as being written by a user called “Alexander“ (although I'm called “Josef Schönberger [GBS ÜL]” on the platform).

There are no error messages in the console. This applies both for Firefox and Chromium. This issue is not only bound to my account, either, a college has the same problems.

Maybe this is an issue with authentication and authorization?

**Comment by Jojaa350** [comment]
A bit more investigation:
- All messages have an userID associated with them, even those from “Anonymous”. Different messages from me have different userIDs, however.
- On the websocket, I got the reply `{"type":"message","channel":"chat/20084","payload":{"code":403,"description":"course only visible for logged in users"}}`. I am the admin for that course.

Definitely looks like a authentication and authorization mixup to me.

**Comment by joschahenningsen** [comment]
Yeah that doesn't look good. This unmoderated chat looked fine today: https://live.rbg.tum.de/w/WiSe22ERA/22942

I'll do a rollback later and investigate this.

**Comment by joschahenningsen** [comment]
> and are display as being written by a user called “Alexander“

Are you sure you're logged in with your account? What name is displayed in the website header?

> People were asking questions as anonymous, although that is not allowed in the course settings

From what I can see here https://live.rbg.tum.de/admin/course/387 anonymous messages should be allowed.

Did you log in using `TUM Login` or an internal account?

**Comment by joschahenningsen** [comment]
@alexanderstephan is not listed as a course admin, is this intended?

**Comment by joschahenningsen** [comment]
I suspect that there might be a race condition ~~that could've been introduced in #834~~ that mixes up chat session contexts because I also randomly get `course only visible for logged in users` when I'm logged in. @mono424 any idea what might be happening?

**Comment by alexanderstephan** [comment]
> @alexanderstephan is not listed as a course admin, is this intended?

I am not sure if I ever was a course admin. 🤔 I think there was no real need.

**Comment by Jojaa350** [comment]
Ok, since ~19:35, this is fixed all of the sudden. Did somebody do a rollback? I just had this issue a few minutes earlier, but that may also be a caching issue then.

> From what I can see here https://live.rbg.tum.de/admin/course/387 anonymous messages should be allowed.

This option was off last time I checked. Either somebody misclicked or something else went wrong. Anyway, let's ignore that part then.

> @alexanderstephan is not listed as a course admin, is this intended?

He never was. But he would also have the “[GBS ÜL]” suffix in his name, so it's not him. Shouldn't all accounts on this TUMlive instance have a surname? My theory of an account mixup may be wrong then.

> Are you sure you're logged in with your account? What name is displayed in the website header?

I am. I just logged in before that using the TUM shibboleth. The name in the bar is displayed correctly. It's the only account I have. I tried logging out and in again, to no avail.

However, I just noticed: My second message was sent by “George”. I know nobody with that name. There was a page reload inbetween, I wasn't able to test whether two messages with no reload inbetween would result in the same author name.

**Comment by Jojaa350** [comment]
This are getting weirder and weirder by the day. It didn't work again right now. I don't know why it worked yesterday, even with multiple reloads. But it doesn't work right now.

**Comment by joschahenningsen** [comment]
> Ok, since ~19:35, this is fixed all of the sudden. Did somebody do a rollback? I just had this issue a few minutes earlier, but that may also be a caching issue then. 

No rollback, just less users -> issue didn't show 

Fyi I just did a rollback, if the issue is not reproducable tomorrow we found the problem. if not I'll probably have a long night :D

**Comment by joschahenningsen** [comment]
Seems to be fixed since #877
