### ISSUE TITLE
Open Stream Button Visibility is Bad

### ISSUE THREAD

**Issue by COM8** [joschahenningsen/TUM-Live#892]
**Describe the bug**
I was searching for 3 minutes on the following page, for where I have to click, to go to the current live stream.

![Screenshot from 2023-01-20 16-33-38](https://user-images.githubusercontent.com/11741404/213741069-255181df-ed07-48ea-b503-ec433cebf542.png)

**To Reproduce**
1. Go to https://live.rbg.tum.de/course/2022/W/jms
2. Search the "> Open stream" button

**Expected behavior**
In my eyes, the "> Open stream" button should be like the "VoDs" and "Upcoming" button, perhaps even in red.

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Browser: chromium/firefox
 - Version: 107.0.5304.121/108.0.1 (64-bit)

**Comment by alexanderstephan** [comment]
I remember some professor had a similar problem here. Maybe the whole island around `Live Now!` could be one big button.
