### ISSUE TITLE
Hide "Skip Pause" button

### ISSUE THREAD

**Issue by berksudan** [joschahenningsen/TUM-Live#916]
One should be able to hide "Skip Pause" button. Because it doesn't always work perfectly and distracts the user by appearing constantly in the screen. I was able to easily block it with "Block Element" option in my ad blocker, so most likely it can be done with "Inspect" in the browser. It would be a simple yet useful feature to hide this button on the screen.

**Comment by joschahenningsen** [comment]
It should probably hide with the other player controls when the user doesn't interact with the player for a few seconds.
