### ISSUE TITLE
Make number button navigation optional

### ISSUE THREAD

**Issue by g-adel** [joschahenningsen/TUM-Live#918]
**Is your feature request related to a problem? Please describe.**
When I'm taking notes on a lecture and I forget to switch the active window and type a number, the video jumps to a completely random time.

**Describe the solution you'd like**
Make the number button navigation an option in the settings below the VoD.

**Comment by MatthiasReumann** [comment]
Hey! A press on `SHIFT+?` will reveal some useful shortcuts for the watch page. As you can see in the image below, the video doesn't jump to a completely random time. 

Regarding the customisability of this feature, I unfortunately have to admit that we are not response for the misuse of window managers.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/29633518/222712139-8519e7f0-f595-4f68-a029-e65195336ec2.png">
