### ISSUE TITLE
Improve visibility of reply mode

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#925]
**Is your feature request related to a problem? Please describe.**
I've seen the problem that people overlook that they are reply mode or even the other way around, that people send a normal message even if they intend to send a reply.
Especially when there is something typed in the chat, the reply mode text is hidden.
There is an indicator around the chat message, but it is not very visible and intuitive.

**Describe the solution you'd like**
One could enlarge the text input field and pin the message at the bottom of the chat.

**Describe alternatives you've considered**
Leave it like it is and maybe just even more bold/aggressive colors

**Comment by MatthiasReumann** [comment]
Agreed. I think the Twitch implementation of this feature could guide the implementation:

<img width="330" alt="image" src="https://user-images.githubusercontent.com/29633518/219934080-bfbd9feb-ef9b-4e29-8665-5b034f2cc900.png">

**Comment by alexanderstephan** [comment]
Yes, that would look great!
