### ISSUE TITLE
Inconsistent Scrolling Behavior

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#926]
**Describe the bug**
The livestream chat is only scrolled down when there is a new message and the corresponding blue banner is pressed.

**To Reproduce**
1. Go to a livestream, e.g., https://live.rbg.tum.de/w/GBS/26257?dvr right now
2. See that the chat is at the uppermost position and does not scroll by default

**Expected behavior**
Livestreams should enable auto scroll by default

**Comment by joschahenningsen** [comment]
Was this fixed already?

**Comment by MatthiasReumann** [comment]
Should be fixed in #1071.
