### ISSUE TITLE
Subtitles not displayed in firefox when only English subtitles are available 

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#936]
**Describe the bug**
When only(?) English subtitles are available, the player doesn't show any subtitles.

**To Reproduce**
1. Create a vod
2. Add English subtitles to the database
3. Open vod -> no subtitle button

**Expected behavior**
The player should have a button that allows selecting the subtitles

**Comment by MatthiasReumann** [comment]
I can't reproduce the bug locally. Neither using the docker-compose build and a local build with an existing VOD. Any more information you could provide so that I might be able to reproduce it? Might caching be a problem?

**Comment by joschahenningsen** [comment]
Have a look at this stream and the network tab: https://live.rbg.tum.de/w/blutest/26421

The subtitle request for English is successful but the subtitle selector in the player is not available. Are the subtitles themselves faulty?

**Comment by CommanderStorm** [comment]
This is a firefox only issue:
![image](https://user-images.githubusercontent.com/26258709/221923288-69186399-e8fc-4765-9192-9a64c53eefd0.png)
(on Chrome latest, linux)

Reproducible on firefox latest, linux

**Comment by joschahenningsen** [comment]
Seems to be related to my firefox [102.8.0esr (64-bit)]. Weird, I'm not getting any related errors or warnings on the console.
