### ISSUE TITLE
Make "Servus" Default

### ISSUE THREAD

**Issue by timofriedl** [joschahenningsen/TUM-Live#939]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to see that instead of the correct Bavarian way of greeting ("Servus"), the incorrect word "Moin" is used by default.
![moin](https://user-images.githubusercontent.com/52008460/221963106-13e08a95-0bc8-43de-a8e5-b3e17c64b795.png)

**Describe the solution you'd like**
Make "Servus [NAME], nice to see you!" the default message.
Optionally, when trying to switch to "Moin", request the user to accept a popup warning asking "Are you sure you want this?".

**Describe alternatives you've considered**
Since this poses a serious threat to Bavarian culture, I cannot think of any alternatives.

**Additional context**
For illustrational purpose, I tried to find a map of the different words to greet someone in Germany, which I unfortunately couldn't. However, the city of Munich is clearly below the moin-Grenze.

**Comment by timofriedl** [comment]
Just saw the other threads about this issue and the option in the settings. Sorry for the duplicate. Still weird that the default greeting is set to "Moin". Should be tweaked.

**Comment by joschahenningsen** [comment]
See #402 #586

This is a deliberate design decision. I'm from northern Germany and added my personal touch here and I'm not particularly keen on removing it.
