### ISSUE TITLE
Extract audio file of recorded lecture

### ISSUE THREAD

**Issue by lptl** [joschahenningsen/TUM-Live#954]
I wish there could be a button to download the audio file of the lecture. Since there is no subtitles, I think I can transcribe the whole lecture to text format. But recording the audio one by one is time-consuming. Are there any recommendations to solve this?

**Comment by joschahenningsen** [comment]
We're working on subtitles (#796) and expect them to be available for all lectures at some point in the next semester. Then you'll be able to download a transcript. Additionally we're thinking about an audio only mode (#789).
Unfortunately we can't offer downloads of lectures without the approval of lecturers but you can download lectures with software like [ffmpeg ](https://gist.github.com/tzmartin/fb1f4a8e95ef5fb79596bd4719671b5d) or [tum_video_scraper](https://github.com/Valentin-Metz/tum_video_scraper) or [youtube-dl ](https://github.com/ytdl-org/youtube-dl)
